### ISSUE TITLE
Exposing parsing functions

### ISSUE THREAD

**Issue by noamross** [yihui/knitr#1026]
I think it would be useful to expose internal functions in knitr (and rmarkdown) that parse document contents and store information.  

A good approach would be to be able to run something like knit_parse() and get a list object with all the components of a knitr document - text chunks, code chunks, chunk options, and header metadata.

One use-case I was recently experimenting with is two-way conversion between Rmd and Jupyter Notebook files.

**Comment by yihui** [comment]
I think it makes better sense for everybody to use JSON, but I have no idea if we will ever get there: https://github.com/yihui/rnotebook (probably no)

On the other hand, since you are just experimenting with the idea, I guess you can use `knitr:::` to access the internal functions. Parsing is a little messy in **knitr** (in the sense that it relies on some side-effects such as `knit_code$set()`), and I'm afraid you will not be able to get what you expected.
