### ISSUE TITLE
knitr markdown produces trailing whitespace for figures

### ISSUE THREAD

**Issue by chiphogg** [yihui/knitr#1049]
When I write a `.Rmd` file, the resulting `.md` file has a space at the end of the line:

`![plot of example](figure/example.png) `

It should have no space:

`![plot of example](figure/example.png)`

(Okay, apparently Github markdown strips the trailing space so that the above two examples look identical.  That's what I want you to do, too!  :)

This is mainly an aesthetic problem, but it also creates friction with some of the tools I use at work.

**Comment by yihui** [comment]
I'm a little surprised that this space can matter. Anyway, I might be able to fix it at some point, but not now. That said, I guess you can define a `plot` hook on top of the default hook to remove the space.

```r
local({
  library(knitr)
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    res = hook_plot(x, options)
    gsub(' $', '', res)
  })
})
```

**Comment by chiphogg** [comment]
Thanks for the workaround. I can use it while I wait for a permanent fix.

**Comment by yihui** [comment]
On second thought, I tend not to change it (it has been there for too long). The Markdown code with a trailing space is syntactically valid, and I guess the tools you use should not be sensitive to the space.

**Comment by chiphogg** [comment]
I don't follow -- why does the length of time it has been around make you not want to change it?

I am using this with a version control system at my work.  The system integrates with tools to check for style guide compliance.  It expects `.md` files that were composed by hand, and it flags trailing spaces as a lint error (a reasonable expectation for hand-composed `.md` files).  If knitr stops emitting these spaces, it makes it easier to write reproducible documentation at work.

**Comment by yihui** [comment]
The length of time was due to certain unfortunate things in my personal life this year.

As I said, the trailing space is not an error. I don't see why it should bother the linter. On the other hand, I have provided a workaround anyway.

**Comment by chiphogg** [comment]
I am truly sorry to hear about your issues.  I hope that you and yours are now well.

Linters are designed to catch both syntax *and style* errors.  That is why it is not inappropriate for the trailing space to cause problems: it is a perfectly reasonable style guide requirement.

Thank you for providing the workaround.  It still seems to me that the best behaviour should be the default behaviour.  I do not know of anybody who *prefers* the trailing space (and would be extremely surprised to find anyone), but I *do* know a valid reason to prefer its *absence*.  Correct me if I'm wrong, but I think it is clear that omitting the space is the better behaviour.

If so, the only remaining question is whether this benefit justifies the cost of your time.  That, only you can answer.

Either way: cheers, and thanks for knitr!

**Comment by yihui** [comment]
I don't know which behavior is better, but I have removed the trailing space anyway. This action is fairly simple by itself, but this simple change may have other consequences, one of which is I need to update my tests, e.g. https://github.com/yihui/knitr-examples/commit/c84b54dce164d5cb269df234f46d8ebbe951a884 Then I have to cross my fingers wishing there are nobody really testing the knitr output in their packages on CRAN, otherwise I may break their tests. That is why I usually say no by default to requests like this unless the issue really hurts (e.g. is a bug).

**Comment by chiphogg** [comment]
Thanks very much!

I wish there were some way to make the tests more forgiving and less brittle.  Besides the changing space, it doesn't seem right for the tests to depend on the imgur filename, for example.  Of course, that would bring its own tradeoffs (e.g., it would probably be less simple to implement).  Oh well.

**Comment by yihui** [comment]
I have total control over my own tests, so that is not big issue for myself. The real concerning issue is CRAN. I cannot stop other package authors from writing tests against white spaces. Having been bitten by one of the famous CRAN maintainers several times in the past, I try to be very conservative even if a change is essentially minor.
