### ISSUE TITLE
using read.csv to populate a parameter value gives YAML parameter error

### ISSUE THREAD

**Issue by aronatkins** [yihui/knitr#1074]
Using a Rmd like:

    ---
    params:
      d: !r read.csv("data.csv")
    ---
    nothing to see

And a data file:

```
a,b
1,2
2,3
```

Running `knit::knit_params` gives:

```
> knit_params <- knitr::knit_params(readLines("file.Rmd"))
Error: no value field specified for YAML parameter 'd'
```

**Comment by yihui** [comment]
That is because a data frame is also a list. I just pushed a fix, which checks if the list was created from an R expression or not. If it was, I think we should use `list(value = param)` instead of checking if `param$value` exists.

@jjallaire Please see if the fix is appropriate. We can revert it if it is not. The repro can be simplified to:

    ---
    params:
      d: !r data.frame(a=1:2, b=2:3)
    ---
    
    nothing to see
