### ISSUE TITLE
Caching doesn't work with externalization?

### ISSUE THREAD

**Issue by CY-Chan** [yihui/knitr#1115]
I've been working on a project that requires me to create a document and a similar beamer presentation with many shared results. I've been trying to use knitr's caching abilities to make this process as streamlined as possible. I successfully got the document and beamer files to share cached files if I have the exact same code chunks in both files. 

However, this is not ideal for future editing as I'd prefer not having to re-paste the code chunks each time I make a change in one file. I thought that externalization through read_chunk would be the natural solution, with both the document and beamer referring to the same external code. However, externalization and caching only appear to work within-file, and is re-cached when I alternate the compiled file.

I am attaching 2 Rnw files with a shared external R file below. Please let me know if I am doing something wrong or if theres a better way of achieving my goal. Thanks!

File1.rnw
```r
\documentclass{beamer}

\begin{document}
<<setup, include=FALSE>>=
  # smaller font size for chunks
  opts_chunk$set(size = 'footnotesize', cache=TRUE)
  read_chunk('main.R')
@

<<test>>=
@

\end{document}
```

File2.rnw
```r
\documentclass[titlepage]{amsart}

\begin{document}
<<setup, cache=FALSE, echo=FALSE, message=FALSE>>=
  library(knitr)
  # global chunk options
  opts_chunk$set(cache=TRUE)
  read_chunk('main.R')
@

<<test>>=
@

\end{document}
```

main.R
```
## ---- test ----
x<- seq(1:10)
```

**Comment by yihui** [comment]
To share the cache between two documents, you should make sure the two chunks have exactly the same chunk options. In your beamer document, you have `size = 'footnotesize'`, but in the amsart article, you don't have that option. 

You can redefine the `knitrout` environment instead of using the chunk option `size`: http://yihui.name/knitr/demo/beamer/

Alternatively, you can set `cache = 2` instead of `TRUE`: http://yihui.name/knitr/demo/cache/

**Comment by CY-Chan** [comment]
Thanks! It works perfectly now.
