### ISSUE TITLE
Using knit2html to knit shiny ui object. How to get rid of <!–html_preserve–> ?

### ISSUE THREAD

**Issue by skranz** [yihui/knitr#1130]
Hi,
in my RTutor package, I use `knit2html` to dynamically knit markdown code and show the resulting html code in an uiOutput field. I would like to extend the functionality to allow the markdown code to contain shiny ui elements. However, I have not figured out how to do that correctly. 

This gist contains a simple example that illustrates the problem I encounter:

https://gist.github.com/skranz/6832705d691ca583a0ef

Here is a screenshot of the resulting app:

![screenshot preserve html](https://cloud.githubusercontent.com/assets/1413022/11168049/6a6fd64a-8b7e-11e5-8001-6122b2365031.PNG)

The problem are that the `<!–html_preserve–>` lines are shown.

Maybe I just used the wrong commands. (E.g. is calling `HTML(html)` correct, or is there a better function?). Or somewhere there is a bug in the toolchain, e.g. in `knit_print.shiny.tag.list`?

I would be glad for any help.

Here is my sessionInfo

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leaflet_1.0.0   knitr_1.11      htmlwidgets_0.5 shiny_0.12.2   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1      digest_0.6.8     mime_0.4         R6_2.1.1         xtable_1.8-0    
 [6] jsonlite_0.9.17  formatR_1.2.1    magrittr_1.5     evaluate_0.8     stringi_1.0-1   
[11] rstudioapi_0.3.1 tools_3.2.2      stringr_1.0.0    markdown_0.7.7   yaml_2.1.13     
[16] httpuv_1.3.3     htmltools_0.2.6 
```

Best wishes,
Sebastian

PS: In this simple example I could manually get rid of the `<!–html_preserve–>` with `gsub`. Yet, in my attempt to include the functionality into RTutor I sometimes get even more messed up HTML. (I am actually working on including knited htmlwidgets as shiny objects, by adapting knitr_print.htmlwidget.) While I already quite blindly tried out a lot of different code lines, I am still not sure what goes wrong. I think a solution to the simple example illustrated above could be very helpful, though.

**Comment by yihui** [comment]
You should use `rmarkdown::render()` in this case. `knit2html()` is for R Markdown v1 only, which is very limited.

**Comment by skranz** [comment]
The huge advantage of `knit2html` over `rmarkdown::render` is that it is much faster (the microbenchmark below suggests a factor around 10). This is a big advantage when interactively rendering user code in a shiny app. So I guess I will still try to figure out a workaround or try to find a clever way to quickly find out when calling the slow `rmarkdown::render` is neccessary (e.g. when there are shiny inputs or html widgets), and otherwise stick with `knit2html` for better performance. 

Concerning your change, https://github.com/yihui/knitr/commit/abbc8f981a49932d46387ecda5c55fefce4feefc, I personally, think it would be better if `knit2html` always only throws a warning instead of an error if it is called on `R Markdown v2`, since sometimes speed may have a higher priority than correct rendering (since small render errors may be fixed with `gsub` ex-post). Also changing `knit2html` now to throw an error may cause errors in existing code that relies on `knit2html`.


```r
# Speed comparison

library(rmarkdown)
library(knitr)

library(microbenchmark)

# test.Rmd is a fairly small Rmarkdown file
text = readLines("test.Rmd")

microbenchmark( times=3,
rmarkdown::render("test.Rmd","html_document"),
knit2html("test.Rmd", output="test.html"),
knit2html(text=text)
)

# Unit: milliseconds
#                                            expr        min         lq      mean
#  rmarkdown::render("test.Rmd", "html_document") 1163.64270 1213.87070 1289.7999
#     knit2html("test.Rmd", output = "test.html")   93.75451  110.80686  122.7250
#                          knit2html(text = text)   91.51911   92.53359  108.8416
#      median        uq       max neval cld
#  1264.09870 1352.8785 1441.6583     3   b
#   127.85920  137.2102  146.5612     3  a 
#    93.54807  117.5028  141.4576     3  a 
```

**Comment by yihui** [comment]
I see. `knit2html()` should be faster than `rmarkdown::render()` since the latter involves Pandoc.

The underlying issue can be more complicated than simply getting rid of `<!–html_preserve–>`. To get rid of these special HTML comments, you may take a look at `?htmltools::htmlPreserve`. I'm not sure if how difficult it is to apply `extractPreserveChunks()` and `restorePreserveChunks()` to your case.

These HTML comments is only one part of the problem. The trickier issue is the HTML dependencies. It may or may not be an issue for you, depending on what functions you call in shiny. textInput() is a simple one that has no extra JS/CSS dependencies, but other inputs may have, for example, sliderInput(). R Markdown v1 / knit2html() does not understand these dependencies.

`knit2html()` is actually a simple wrapper of `knit()` plus `markdown::markdownToHTML()`, and I'd recommend you to call these two functions directly if you intend to manipulate the HTML output. This R Markdown v1 vs v2 issue seems to be confusing to quite a few users, and I think it's worth an error message so users are aware of the potential problems that they may run into.

I have added an argument `force_v1` to `knit2html()`; when it is `TRUE`, `knit2html()` renders the input file as an R Markdown v1 document even if it is for R Markdown v2.

**Comment by ptaal** [comment]
Hi,
My temporary (not complex) solution for getting rid of the `<--html_preserve--><!--html_preserve-->` was as follow:

```
---
title       : "shiny document"
subtitle    : 
author      : 
job         : 
framework   : html5slides
highlighter : highlight.js
hitheme     : tomorrow
widgets     : []
mode        : selfcontained
knit        : slidify::knit2slides
output      : html_document
runtime     : shiny 
--- {class: class1, id: id1, bg: white}

## Slide1

```{r, results='asis'}
text <- textInput("myInput", "Enter text", "Hello World")  
print(text)
```
This is probably a very simple (basic) solution, yet it helped me out and I'm hoping that it would helps others, too.

Best,
Pouria
