### ISSUE TITLE
option to print debug messages to console during R markdown processing

### ISSUE THREAD

**Issue by shyamrallapalli** [yihui/knitr#1133]
I have R markdown files where i run an analysis and produce results and graphs based on the analysis.
Analysis involves going through 100s of files and it take some time about (10-15 mins)
and i would like print some debug message as a status indicator.

I know you have following type of log messages during conversion processing
```
  |.......                                                          |  11%
  ordinary text without R code

  |..............                                                   |  22%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |......................                                           |  33%
  ordinary text without R code

  |.............................                                    |  44%
label: analysis (with options) 
List of 1
 $ include: logi FALSE

  |....................................                             |  56%
  ordinary text without R code

  |...........................................                      |  67%
label: boxplot (with options) 
List of 3
 $ echo      : logi FALSE
 $ fig.width : num 12
 $ fig.height: num 12
```

but until it goes to next step (from analysis to boxplot) i have a no progress indicator due to the time taken for analysis.
Any option or indicators would be of great help

**Comment by yihui** [comment]
If you use Windows, there is a `winProgressBar()` function that you may use to create a progress bar in the GUI. For other platforms, you may consider `tcltk::tkProgressBar()`. In either case, you have to manipulate the progress bar by yourself. There isn't an automatic approach that gives you a progress bar. You may google for "R progress bar" for more solutions, but please bear in mind that the text progress bar (`txtProgressBar()`) won't work in **knitr** since the stdout will be redirected and you won't see the text progress bar if it is created inside a code chunk.

BTW, you may consider asking questions on StackOverflow in the future: http://stackoverflow.com/questions/tagged/knitr

**Comment by shyamrallapalli** [comment]
thank you yihui,
tkProgressBar() is enough for me
i had tried with txtProgressBar() before post it here
And apologies for my ignorance, in future would raise issues at StackOverflow
