### ISSUE TITLE
out.extra = "" uses backslash instead of forward slash in filepath on windows

### ISSUE THREAD

**Issue by ThierryO** [yihui/knitr#1136]
Minimal example

    ---
    output: pdf_document
    ---
    
    ```{r pressure, echo=FALSE, out.extra=""}
    plot(pressure)
    ```

current output with knitr 1.11.20

    ---
    output: pdf_document
    ---
    \includegraphics{c:\tmp\test_files/figure-latex/pressure-1} 

The backslashes generate an error when compiling the latex file.

Desired output

    ---
    output: pdf_document
    ---
    \includegraphics{c:/tmp/test_files/figure-latex/pressure-1}

**Comment by yihui** [comment]
I wonder how the figure path became an absolute full path. You provided a minimal example but I don't know how to reproduce the problem. How did you compile this R Markdown document?

**Comment by ThierryO** [comment]
It might be a problem with the rmarkdown package. I can reproduce it with

    setwd("c:/")
    rmarkdown::render("tmp/wrongpath.Rmd", output_dir = "tmp", clean = FALSE)

**Comment by yihui** [comment]
Generally I do not recommend you to use `output_dir`. Things can become very tricky when you leave the current working directory. Does this work?

```r
setwd("c:/tmp")
rmarkdown::render("wrongpath.Rmd", clean = FALSE)
```

If you want to generate the output to another directory, I'd recommend you to generate it to the current working directory, then use `file.rename()` to move the output to a different directory.

**Comment by yihui** [comment]
I just tested it on Windows, and it is an issue of rmarkdown instead of knitr: https://github.com/rstudio/rmarkdown/blob/558e380f984aa9e9fa9be43b770c0199ccafd24a/R/render.R#L256

As I said, this issue can be very tricky, and the alternative approach I mentioned is way simpler internally. Had I known the `output_dir` argument of `render()` earlier, I'd have strongly voted against it when developing the rmarkdown package.
