### ISSUE TITLE
automatically add appropriate cache.extra for source() etc commands in chunks

### ISSUE THREAD

**Issue by maxheld83** [yihui/knitr#1141]
I often `source()` quite computationally expensive scripts within an `*.Rnw`, and I a) would like therefore to have these results cached, and b) have it *automatically* rebuild the cache if something changes in the `source()`ed script.

I imagine this is a relatively common scenario, and a "gotcha"-aspect of knitr caching: it's easy to forget that while a chunk is re-cached if its string content changes, it *will not be re-cached* if some downstream, sourced script changes (makes sense, of course).

I've now solved this like so:

```
<<simulations, cache.extra = tools::md5sum("R/simulations.R")>>=
# this also caches again whenever the content of R/simulations.R has changed
source("R/simulations.R")
@
```

so, whenever I source a script, I also add a `cache.extra` to that effect.

Would it be feasible/desirable to add this kind of functionality as a default option, whenever a `source()` etc. are used?
Or does this just create more headaches for everyone?

**Comment by yihui** [comment]
If `source()` is the only thing you do in a code chunk, I'd recommend you to use this solution: http://stackoverflow.com/a/31216122/559676 Otherwise I guess I'd leave it to you to decide when to invalidate the cache, because it will be tricky to detect such external dependencies automatically (e.g. someone could write a function that calls `source()`).

**Comment by maxheld83** [comment]
uh yes, thanks, that's what I ended up doing (I realize now I don't even need to hash it).
I see/agree that automating this would only be a bag of hurt.
