### ISSUE TITLE
declare, extract, or remove 'rst2pdf' dependency

### ISSUE THREAD

**Issue by trevorld** [yihui/knitr#1148]
CRAN wants me to declare an 'rst2pdf' SystemRequirement dependency on a couple packages with reStructured Text vignettes even though the vignetteBuilder 'knitr' is the package that actually requires it.  Since 'knitr' could feasibly remove this dependency in the future in favor of pandoc (or other rst-aware tools)  it doesn't make a lot of sense to make such a SystemRequirement declaration on my end since my packages are agnostic on which system tool 'knitr' uses to process the reStructuredText.

I see three possible solutions:

1) Extract the rst2pdf code into a new package which explicitly declares it as a SystemRequirement.  This could just be the rst vignette building code (which CRAN is now complaining about even though I've been using it for a couple of years) or could also include the 'rst2pdf' function which has the undeclared dependency.
2) Remove the dependency by instead handling reStructuredText vignette code using pandoc (whose SystemRequirement should be satisfied by knitr's suggested package rmarkdown).  Could directly make html vignettes or indirectly make pdf vignettes via latex.
3) Directly declare a SystemRequirement in 'knitr' on 'rst2pdf'.

I could help with whichever approach you'd think would be best.

**Comment by yihui** [comment]
It is simple for me to add rst2pdf to `SystemRequirements`, and my only concern is that it looks confusing because rst2pdf is not really **required** for the core functionality of knitr to work. It is more like `SystemSuggests`. I guess there are only a handful of people actually using `rst2pdf()` in knitr. The vast majority are using R Markdown.

That said, I will just add rst2pdf to SystemRequirements if that makes CRAN happy. Making CRAN happy is always my top priority. Sometimes it just wastes more time of everybody if we choose to argue over these trivial things. I'd spend these 30 seconds on doing whatever they want no matter I like it or not.
