### ISSUE TITLE
function to include htmlwidgets in html documents no longer working in dev version of knitr

### ISSUE THREAD

**Issue by vnijs** [yihui/knitr#1192]
@NikNakk posted a function on SO to include htmlwidgets in knitted documents (http://stackoverflow.com/a/31797947/1974918). This has worked well for me with DiagrammeR plots and DT tables. However, with the dev version of knitr on github the function has stopped working because it tries to use webshot even when knitting to html. I can setup an example in a repo if that would be helpful.

<img width="843" alt="screen shot 2016-04-08 at 12 13 59 pm" src="https://cloud.githubusercontent.com/assets/2998956/14395000/ff8d0b36-fd83-11e5-86f6-0386a15ae8c7.png">

With the version of knitr on CRAN:

<img width="824" alt="screen shot 2016-04-08 at 12 23 03 pm" src="https://cloud.githubusercontent.com/assets/2998956/14395120/aeb8e24c-fd84-11e5-8a64-44d2c4dabe50.png">

**Comment by yihui** [comment]
The answer on SO was only an incomplete hackish solution. HTML widgets are not expected to work with R Markdown v1. If you want them to work in v1, a complete solution should be based on https://github.com/rstudio/rmarkdown/blob/master/R/html_dependencies.R The only advantage of R Markdown v1 over v2 is speed, at the price of much less power than Pandoc. Other than that, I don't see any reason to stay with R Markdown v1.

**Comment by vnijs** [comment]
Thanks for the input @yihui. I use v1 in a shiny app that is intended to run locally. Although I recommend running from Rstudio I'd prefer not to **require** Rstudio / pandoc. Apparently it did work with v1 before and it seems useful, at least to me. Is there a specific reason this is not supported?

**Comment by yihui** [comment]
It worked due to the fact that you applied a hack. As I said, HTML widgets are not supposed to work with R Markdown v1, and they do not really work out of the box. You must copy the dependency files of widgets. R Markdown v1 does not do that, so widgets won't work. I think we either completely support HTML widgets in R Markdown v1, or just do not support them at all. We do not really have much interest in R Markdown v1 any more, so it is unlikely that we will continue to invest time in it. That said, if you are interested in creating a pull request, please feel free and we'd love to consider it. It is probably not too complicated.

To clarify, RStudio is not required. Only Pandoc is required for R Markdown v2. I understand an extra package dependency may be a burden, but for Pandoc, it is very much worth it.

**Comment by yihui** [comment]
You can use the chunk option `screenshot.force = FALSE` to go back to the old behavior.

**Comment by vnijs** [comment]
Thanks @yihui!
