### ISSUE TITLE
Feature request: option to add multicolumn headers

### ISSUE THREAD

**Issue by simonthelwall** [yihui/knitr#1208]
I regularly need to add spanning column names to tables in reports. Unfortunately, there doesn't seem to be a way to do this in kable to Word. Would it be possible to add this?

**Comment by yihui** [comment]
Sorry that is not on the plan for `kable()`. You may try the pander package instead.

**Comment by simonthelwall** [comment]
ok, thanks anyway.

**Comment by yasirs** [comment]
@yihui Is there a way to make pander play nice with kable with regards to latex labels? kable, when writing documents with bookdown for eg., can add \label to tables for cross-referencing. Since pander writes to markdown, and there is no specification for table labels possible in md, pander can't possibly add labels.

I guess going forward, if pander can't be used for tables in newer packages, shouldn't kable handle advanced features?

**Comment by yihui** [comment]
@yasirs Sorry but personally I'm not interested in tables (I know many find tables useful), so this does not have priority on my todo list. If you want pander to support anything, you may contact the pander author.

**Comment by yasirs** [comment]
Sure ... do you think you'll be open to pull requests adding features to kable?

**Comment by yihui** [comment]
Yes, but I hope it is not going to be too much code to be added. Thanks!
