### ISSUE TITLE
RJDBC no dbGetRowCount() method implemented

### ISSUE THREAD

**Issue by mattwg** [yihui/knitr#1271]
Hi Yihui, I am trying to use the SQL code chunks with an RJDBC connection.  The RJDBC package does not seem to implement the DBI.dbGetRowCount() method - I read through the RJDBC code [here](https://github.com/s-u/RJDBC/blob/master/R/class.R).  This results in an error from [this line](https://github.com/yihui/knitr/blob/master/R/engine.R#L429) when I try and run the SQL code in the chunk, specifically:
unable to find an inherited method for function ‘dbGetRowCount’ for signature ‘"JDBCResult"’
Do you need to check the dbGetRowCount?  I forked the project [here](https://github.com/mattwg/knitr/blob/master/R/engine.R#L429) and went straight for the dbFetch and it seems to work - but not sure what other tests this might break.  
Matt

**Comment by yihui** [comment]
Is it possible to request @s-u to implement the `dbGetRowCount()` method in RJDBC? If not, we can certainly `try()` here. The reason that we check the number of rows is that some SQL statements may not return any data, such as `INSERT`/`UPDATE`/`DELETE`/...

cc @jjallaire @javierluraschi

**Comment by javierluraschi** [comment]
@jjallaire and @yihui:

Before `DBI 0.5`, DDL statements (`CREATE`, `INSERT`, etc) had to be executed through `dbSendQuery` or `dbGetQuery`. While this might have worked for multiple backends, some of them, like `JDBC`, required different commands for query and update statements (see http://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html#executeQuery(java.lang.String) `executeQuery` vs `executeUpdate`).

`DBI 0.5` introduces `dbExecute` so I believe we should detect ourselves if the statement is an update statement and use `dbExecute`or `dbSendQuery`/`dbGetQuery` appropiately.

Since we will need to detect ourselves if a statement is an update for `DBI 0.5` anyways, I think we should use this issue to implement this functionality to replace this line https://github.com/yihui/knitr/blob/master/R/engine.R#L429

I can take a look at this.

**Comment by javierluraschi** [comment]
PR: https://github.com/yihui/knitr/pull/1278
