### ISSUE TITLE
kable Error in x$sizingPolicy : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by feng5** [yihui/knitr#1312]
```
library(tidyverse)
library(knitr)
kable(mtcars[1:5, ], caption = "A knitr kable.")
```
the same code work well in markdown with html_document but got error with html_notebook output

**Comment by yihui** [comment]
@jmcphers @kevinushey Any ideas? `kabel()`'s output class is `knit_asis`. Does notebooks treat it as HTML widgets for some reason?

**Comment by kevinushey** [comment]
We indeed do try to treat the output of `kable` in a similar way to an `htmlwidget` -- I believe this is primarily because we need to figure out whether the generated text should be colored white or black, and this depends on the editor background color. Either way this is definitely a bug on the IDE side.
