### ISSUE TITLE
Vertical alignment of subfigures

### ISSUE THREAD

**Issue by gwotto** [yihui/knitr#1327]
This question is related to the StackoverFlow post
http://stackoverflow.com/questions/30664820/subfigures-stacked-vertically-with-knitr
that never received an aswer and
http://stackoverflow.com/questions/12546365/subfigures-or-subcaptions-with-knitr
where the problem is also mentioned
I can use subfigures using knitr in the way described there, but they are always aligned horizontally. It would be an awsome feature to be able to introduce line breaks, so subfigures can be aligned vertically, can be aligned as a 2x2 grid etc...

http://stackoverflow.com/q/40932462/559676

**Comment by stla** [comment]
Perhaps you can achieve this with the package [oaReporting](https://repos.openanalytics.eu/html/oaReporting.html).

**Comment by stla** [comment]
@gwotto I've just replied on SO.

**Comment by eliocamp** [comment]
This could be achieved natively and more elegantly with a `ncol`/`nrow` argument. Would this be a possible improvement, @yihui ?

**Comment by yihui** [comment]
@eliocamp You mean `par()` in base graphics, right? It is easy to layout multiple plots in any way you want, but the problem is subfigure captions.

I have never tried subfigures with R Markdown documents, so I don't really know the answer at the moment.

**Comment by eliocamp** [comment]
I was talking about [this](https://github.com/yihui/knitr/issues/493) problem, which is related to this one.  Using `par()` doesn't cut it because is specific to base graphics and, as you say, does not allow for subcaptions. 

What I'm wondering if knitr can have a `ncol` chunk option that puts linebreaks between subfigures. That would solve this issue and the linked one above. So, for example, this:

```
```{r pressure, out.extra = "", echo = FALSE, fig.show = "hold", fig.cap = "Pressure", fig.subcap = c("one","two"), ncol = 1}
plot(pressure)
ggplot2::qplot(temperature, pressure, data = pressure)```
```
Returns this: 

```
\begin{figure}
\subfloat[one\label{fig:pressure1}]{\includegraphics{test_files/figure-latex/pressure-1} }
\subfloat[two\label{fig:pressure2}]{\includegraphics{test_files/figure-latex/pressure-2} }\caption{Pressure}\label{fig:pressure}
\end{figure}
```

And I'm saying it could return this:

```
\begin{figure}
\subfloat[one\label{fig:pressure1}]{\includegraphics{test_files/figure-latex/pressure-1} }
\newline
\subfloat[two\label{fig:pressure2}]{\includegraphics{test_files/figure-latex/pressure-2} }\caption{Pressure}\label{fig:pressure}
\end{figure}
```

I think a small change in `hook_plot_tex()` that adds `\newline` after.... `align2`? could do it. But I'm just know reading the source code, so I might be wrong.

**Comment by yihui** [comment]
@eliocamp I see. Actually I think you are getting close. A new chunk option `fig.ncol` sounds like a good idea to me, but I don't have time for this task. You are welcome to play with it, and send a pull request. Thanks!

**Comment by eliocamp** [comment]
I'll try that. Although now I'm thinking that maybe it would be better to use the `\subfigure` environment from the `subcaption` package instead of `\subfloat`. From what I see, it wraps figures correctly. 
If there's a reason for using `\subfloat` I'll try the `\newline` route. If not, I can try to get `\subfigure` working. 

I guess fixing `\subfloat` would be the more backwards-compatible way of doing things.

**Comment by eliocamp** [comment]
Scratch that. It was nonsense. There's the pull request.

**Comment by yihui** [comment]
If you need an R Markdown example, please see https://github.com/yihui/knitr/pull/1444#issuecomment-346239114

For an Rnw example, see 119: https://github.com/yihui/knitr-examples
