### ISSUE TITLE
Feature request: change chunk background color in RMarkdown

### ISSUE THREAD

**Issue by AmeliaMN** [yihui/knitr#1333]
As [discussed on StackOverflow](http://stackoverflow.com/questions/41030477/changing-chunk-background-color-in-rmarkdown), I would like to have a certain code chunk highlighted in a different color (e.g. red) to indicate that it is bad practice. If I was using `.Rnw`, I could add the chunk option `background = 'red'` and get what I want, but this does not seem to work in `.Rmd`. 

@jennybc seconded this request, and @ijlyttle has a solution that might turn into a PR!

**Comment by ijlyttle** [comment]
As a first thought, I am thinking to propose a new "standard" chunk option called `class.html`. It would be the end-programmer's responsibility to provide a bit of css to tell the browser what to do with the class.

Q: I am thinking `class.html` to indicate that this may be useful only for HTML, and to try to fit in with the existing naming scheme. Is this the "right" name? My feelings will not be hurt if it is not.

Q: Does this strike the right balance between being useful in the general situation, but not-too-cumbersome for the specific situation that @AmeliaMN wants to solve?

**Comment by yihui** [comment]
Yes, users have to provide the CSS themselves. This can actually be done via the `css` engine in knitr, e.g.

    ```{css}
    .red { background-color: red; }
    ```

For the option name, does `html.class` sound better? I don't know how this could be useful to non-HTML output (otherwise `class.html` will be a better name).

For the second Q, I think this can be useful in general. The only thing that I'm a little concerned about is whether `html.class` should only be applied to the source code chunk, or also to the text output. Maybe there should be another option that controls the latter, e.g. `html.class.output`. I tend to make `html.class.output = html.class` by default, and users can choose to turn it off explicitly by `html.class.output = NA`.

**Comment by ijlyttle** [comment]
I did not know about being able to put CSS directly into knitr! 

`html.class` works for me - I have no idea if this could be useful to non-HTML - you have a much better view of this than I do.

Following your source/output reasoning, how about `html.class.source` and `html.class.output` that could be set independently? Then `html.class` could be used to set both.

For the @AmeliaMN case, you could then set only `html.class.source`.

**Comment by yihui** [comment]
Let me list the pros and cons in my eyes:

- `html.class` + `html.class.output`: if the major use case is to apply the class to both source and output, this combination wins, because only `html.class` is likely to be used, and this name is short. In other words, users opt-out by `html.class.output` (style output unless I tell you not to).

- `html.class.source` + `html.class.output`: if the major use case is to apply CSS classes to source and output separately, this is a better combination (don't style output unless I tell you to). The names are long.

From @AmeliaMN's original question, it seems to me that she only wants to highlight the source code, so perhaps the second combination is better.

Personally I don't like long names, and since this feature is mostly useful to HTML output, we can probably leave out the `html.` prefix, i.e. just `class.source` and `class.output`. I can think of one possible use case for `class.output`, though:

    ```{r class.output='html'}
    cat(as.character(htmltools::p('a paragraph')))
    ```

The output can be syntax highlighted by Pandoc:

    ```{.html}
    <p>a paragraph</p>
    ```

**Comment by ijlyttle** [comment]
Sounds good - I will start out using `class.source` and `class.output`.

**Comment by ijlyttle** [comment]
Just a heads-up to @AmeliaMN and @jennybc that this feature is ready-to-go in the dev version of knitr. If there is something here you think should be done differently, please let me know.

As it stands, you can add a class to either your source and/our your output using options `class.source` and `class.output`. If you are using Bootstrap, you can even avoid adding your own css by using the Bootstrap background classes ([link](http://getbootstrap.com/css/#helper-classes-backgrounds)).

For example:

    ```{r df-drop, class.source='bg-warning', class.output='bg-warning'}
    mtcars[, "mpg"]
    ```

**Comment by yihui** [comment]
Adding a preview of the example 116: https://github.com/yihui/knitr-examples/

![image](https://cloud.githubusercontent.com/assets/163582/21156380/3c51df94-c13b-11e6-8c58-4d8d8853458a.png)
