### ISSUE TITLE
R output in different colour

### ISSUE THREAD

**Issue by Hamedhm** [yihui/knitr#1376]
Hi,

The issue with the knitr is that I want the R output to be in different colour. Can you include this option please?

**Comment by yihui** [comment]
Sorry, the question is too brief, and I have no idea about what you are asking. Please provide an example and possibly some illustrations of what you want.

**Comment by Hamedhm** [comment]
Thank you for your reply @yihui . 
For example, I want all R results (texts) to be in bold and green. But the actual code be in default colouring format (like red for functions, green for variables and so on).

**Comment by yihui** [comment]
When I said "please provide an example", I meant an example document, otherwise I don't know which type of documents you were talking about. Rmd? Rnw? HTML? PDF? Word? There are so many possibilities.

Since this sounds more like a question instead of a bug report or feature request, I recommend you to ask it on StackOverflow instead: https://yihui.name/knitr/faq/ (FAQ 2)

**Comment by Hamedhm** [comment]
sorry it is a Rnw file
