### ISSUE TITLE
Add interactive=TRUE/FALSE chunk option

### ISSUE THREAD

**Issue by franknarf1** [yihui/knitr#1380]
I was trying to print startup messages for the data.table package in my bookdown, but ran into a snag because `data.table:::.onAttach` hides those messages when `interactive()` evaluates to FALSE. [My question on SO](http://stackoverflow.com/q/42841219/) has some further discussion in the comments.

So, I'm thinking it would be nice if knitr could somehow get around this. I saw littler [supports such a flag](http://stackoverflow.com/a/17328254/), and figured that was enough reason to post a hopeful FR.

**Comment by yihui** [comment]
This cannot be done only with with my effort of providing a chunk option. data.table has to respect this chunk option if I provide it. How it can respect this chunk option remains a question and the answer is unclear to me.

Frankly I don't like either this idea (it will be a burden of both me and the author of data.table), or the idea of hacking the `interactive()` function. I think this is way way too much effort to achieve a totally trivial goal, which is to point your readers to the training materials of data.table. If I were you, I'd just say "visit the data.table homepage: http://r-datatable.com".

Instead of having me provide a chunk option, there are two easier ways to achieve your goal:

1. Render your document in an interactive R session;

2. Or ask Matt to respect a global R option like `options('data.table.startup.message')`; then you can set this as an R option instead of knitr chunk option.

Even if we get it working, you cannot guarantee that the package startup message always contains links to the training materials: what if Matt changes the startup message in the future?

RE: littler: littler can provide a flag because it is under the full control of Dirk; by comparison, none of us (me or Matt) has control over base R, so we cannot change the behavior of `interactive()` (without ugly hacks). It may be undesirable to change its behavior, too, e.g. certain code may really only work with interactive R sessions.

Lastly, I don't even like package startup messages myself. I especially hate seeing the same messages over and over again every time I load a package. It makes perfect sense for the first-time user to read the message, but it will become annoying noise soon. For that reason, I very much prefer using an FAQ page instead of bothering users all the time. This is just my two cents not directly related to your problem.

**Comment by franknarf1** [comment]
That makes sense and those are good points. Moreover, I cannot think of any other applications for this feature (and I'm not even sure I'll end up using it here). Thanks for thinking it over.

I see you tagged it with a milestone, but I guess it's better off closed.

**Comment by yihui** [comment]
Thanks! I marked the milestone just hoping to close this issue before I release the next version.
