### ISSUE TITLE
Can't copy single quotes from pdf - sometimes

### ISSUE THREAD

**Issue by cdriveraus** [yihui/knitr#1430]
When copying and pasting from knitr or verbatim blocks, the single quotes are not copied, at least when using adobe reader. I realise it's not a strictly knitr issue, but seems relevant, since it is important to be able to copy these from documents. Using the upquote from the textcomp package lets me copy single quotes fine.

Full details and code here - just not many responses so far!
https://tex.stackexchange.com/questions/388821/cant-copy-certain-characters-inverted-commas-from-pdf

**Comment by yihui** [comment]
In general, you should not expect copying from PDF to just work, since PDF is not a plain-text format. There are many possible problems with text in PDF, such as ligatures. Different PDF readers can behave differently. For example, I have no problem with copying the quotes on macOS (using the Preview app). Anyway, I don't think this is an issue that I could help you with from knitr's side. Your best bet is probably TeX.SE. Thanks for the report!

**Comment by cdriveraus** [comment]
Ok cheers. In the end the fix was simple, just not something I'd encountered before - and yes definitely not something for knitr to deal with, just a historical latex thing. Included answer in the tex post now.
