### ISSUE TITLE
Check if httr and xml2 are available

### ISSUE THREAD

**Issue by jennybc** [yihui/knitr#1436]
Would you be willing to use `requireNamespace("httr", quietly = TRUE)` and `requireNamespace("xml2", quietly = TRUE)` inside `imgur_upload()` to test if they're available and then message accordingly? People sometimes get errors from reprex because it uses `knitr::imgur_upload()` and they might not have these packages installed. TBH the reports I have are re: RCurl and XML, but I think that's neither here nor there. The switch to httr & xml2 doesn't seem to have changed this particular situation. This would produce a more constructive error message re: why things aren't working.

**Comment by yihui** [comment]
I recently switched from RCurl/XML to httr/xml2 (#1433).

Anyway, if these packages are not installed,the error message should look like this:

```r
> knitr::imgur_upload('foo.png')
 Error in loadNamespace(name) : there is no package called ‘httr’ 
```

To me, this error message is sufficient (I need to install the package), but I understand some users may not know what's going on.

Personally I don't want to do `require()` + a custom error message in knitr for this case, since this is not an essential function. For the reprex package, however, I'd recommend that you add RCurl/XML (for the current CRAN version of knitr) or httr/xml2 to Imports, since `imgur_upload()` plays a much more important role there.

**Comment by jennybc** [comment]
OK I will think about what I want to do in reprex.
