### ISSUE TITLE
support for the C++ with cling

### ISSUE THREAD

**Issue by jtianling** [yihui/knitr#1452]
[cling](https://github.com/root-project/cling) is a cling C++ interpreter, and it support Jupyter [here](https://cdn.rawgit.com/root-project/cling/master/www/jupyter.html)

why not add the support for it? Current way to run C++ in rmarkdown is not good enough.

**Comment by jtianling** [comment]
btw: there are more interpreter commands
Matlab: matlab -nodisplay -nojvm -nosplash < main.m
Mathematica: MathKernel -script main.wl

**Comment by yihui** [comment]
Thanks, but I don't really know C++, so if you want to support a new engine, the best way is to bring a pull request: https://github.com/yihui/knitr/blob/master/R/engine.R Thanks!

**Comment by jtianling** [comment]
It's a sad thing because I don't really know R, I just a R markdown user and love to write doc in R markdown with python and ruby.

**Comment by jtianling** [comment]
Maybe you could tell me more info that how to add engine in engine.R.

Though I don't know how to use local R package in source now.

**Comment by yihui** [comment]
I guess it will be hard then, since I don't know C++ and you don't know R. I don't have detailed documentation on how to contribute a new engine. The only documentation is Chapter 11 of the knitr book: https://yihui.name/knitr/ but unfortunately the book is not free. So the only practical documentation is the source code in engine.R.

**Comment by jtianling** [comment]
If I learned R better, there should be a way, maybe in future.
