### ISSUE TITLE
Tangled R file has trailing whitespaces

### ISSUE THREAD

**Issue by mb706** [yihui/knitr#1476]
When tangling an R-Markdown file that has `eval = FALSE` set, the corresponding block in the output file is the input with each line prepended with a comment marker and a whitespace. This results in lines with trailing whitespaces if the original block contains empty lines. Similar to #1049, trailing whitespaces can be annoying if an automated linting system flags them as errors (since they usually result from sloppiness).

Example:
````
```{r, eval = FALSE}
a

b
```
````
results in (I replaced trailing whitespace with underscores):
```
## ---- eval = FALSE-------------------------------------------------------
#  a
#__
#  b
```
(the output apparently differs slightly between going the `purl` route or using the knitr vignette engine that uses `hook_purl`)

The simplest workaround that I can see is to set all `eval = FALSE` blocks also to `purl = FALSE`, but it would be useful if this were the default behaviour, or if there were a simple setting to do this.

(The other solution I can see besides just firing up a script after `buildVignettes` is to basically re-implement `hook_purl` with a one line change within my document, which seems quite inelegant.)

**Comment by yihui** [comment]
Sigh, trailing spaces are not harmful, and they are invisible to human eyes. I think linters should be forgiving. It makes sense to warn against excessive spaces elsewhere, e.g., between variables and operators, because they affect the readability of code.

Personally I appreciate linters and style guides, but I won't follow all the rules. Sometimes I feel linters are overdoing the work.

That said, I guess this issue could be fixed at some point, but not right now. A new version of knitr was submitted to CRAN three weeks ago and stuck there for unknown reasons. Until it is published, I don't plan to work on knitr.
