### ISSUE TITLE
Setting `out.width` without `out.height` will not enlarge smaller images (pdf)

### ISSUE THREAD

**Issue by mathematicalcoffee** [yihui/knitr#1477]
Sorry - I am not quite sure if this is an rmarkdown bug or knitr bug. It is to do with the rmarkdown latex template, but it's a knitr option.

If

* pdf (latex) output
* specify `out.width` on a chunk
* include a graphic that is smaller than the `out.width`,

then

* the image is not resized larger

(when compiling using `rmarkdown::render`).

## example

~~~
---
title: "test"
output:
  pdf_document:
    keep_tex: true
---

First I create an image with imagemagick.

```
convert magick:rose rose.png
```

It is 70x46 pixels.

Then I include it using `knitr::include_graphics` at its normal size

```{r, fig.cap="Rose at its usual size"}
knitr::include_graphics('rose.png')
```

Then I scale it up to be 50% linewidth (as an aside, I need to escape the % symbol
in the fig.cap).

```{r, fig.cap="Rose at 50\\% linewidth", out.width='50%'}
knitr::include_graphics('rose.png')
```

It does not change in size. I have to set the height also.

```{r, fig.cap="Rose at 50\\% linewidth and textheight", out.width='50%', out.height='\\textheight'}
knitr::include_graphics('rose.png')
```
~~~

## expected output

The second image should be 50% of the line width (enlarged).

## actual output

The second image is still the original size, 70x46.

## details

On examining the `.tex` file, the LaTeX is fine. There is a 

```
\includegraphics[width=0.5\linewidth]{rose} \caption{Rose at 50\% linewidth}\label{fig:unnamed-chunk-2}
```

so the `0.5\linewidth` is being propagated correctly.

## why

It seems to be to do with the `\maxwidth` and `\maxheight` in the rmarkdown latex template (e.g. `~/R/library/3.3/rmarkdown/rmd/latex/default-1.17.0.2.tex`): the code that stops the images from overflowing the page by setting the default options to `width=\maxwidth, height=\maxheight, keepaspectratio`.

This sets the default width, height to the width, height of the input image (ie 70x46). 
Then I set `out.width='50%'` so we get height=46 pixels, width=0.5\linewidth.
However `keepaspectratio` keeps the image so it fits in the supplied dimensions, so it keeps the height to 46 pixels and doesn't resize it.

## fix

To fix it you have to set the out.height to \textheight (or something large) so that the image is properly enlarged. Perhaps this is not a bug, but at the very least it is unintuitive and not mentioned anywhere in the documentation for chunk options `out.width` and `out.height`.

For me (if I don't want to remember to set `out.height` to some guessed value every time I set `out.width`) I can fix it by adjusting the template (in the rmarkdown package)

```
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
```

to

```
\setkeys{Gin}{width=\linewidth,height=\textheight,keepaspectratio}
```

Then smaller images will be enlarged and larger images will be shrunk.
However I do not know if this will have unintended consequences, like making images overflow the margins or something. If I make this change have a chunk with no `out.width` and no `out.height`, the image is not enlarged to the whole page size, but maybe that doesn't hold in general.

Alternatively, add a note to the `out.width`/`out.height` chunk option documentation to explain that if `out.width` is set and the image is smaller, you must also set `out.height` (to something large) in order for the image to be enlarged.

## package details

I have this problem with rmarkdown 1.8.5, knitr 1.17.20.

However I also had it with whatever the current versions are with R 3.3 (from CRAN). Sorry, I do not have the specific version numbers, because I (incorrectly) thought this was a pandoc problem so updated my local pandoc to 2.0.x, which prompted me to have to update rmarkdown (which went to 1.8.5) and I updated knitr with devtools while I was at it, and forgot to note the previous version numbers.

I suspect any rmarkdown that uses the `\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}` will have this problem.

## Aside

I did not realise that percent signs in `fig.cap` should be escaped for LaTeX (or else it thinks they are a comment) though it makes sense. I had assumed knitr would do it for me. Perhaps add a little note in the `fig.cap` documentation about this?

**Comment by yihui** [comment]
You are absolutely correct about the root cause: the problem comes from `\setkeys{Gin}` in the LaTeX template:

https://github.com/jgm/pandoc-templates/blob/ee2890c9dc/default.latex#L186-L189

Strictly speaking, this is not a **knitr** issue (as you discovered, **knitr** did the right thing), but since **rmarkdown** is closely related to **knitr**, it is okay to discuss the issue here.

As you have discovered, the only way to override the width and height is to override both of them at the same time, unfortunately. I think the most appropriate fix is to provide an option (variable) in Pandoc's LaTeX template to disable this "smart" feature (e.g., `$if(graphics-maxwidth)$`). Otherwise you have to provide your own LaTeX template: http://rmarkdown.rstudio.com/pdf_document_format.html#custom_templates

---

Re: Aside

Portability is hard. R Markdown is not only for PDF. `%` is a special character in LaTeX output but not in other output formats; it will be problematic no matter if you escape it or not. Currently the only way to achieve portability is bookdown:

- https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references
- https://bookdown.org/yihui/bookdown/a-single-document.html
