### ISSUE TITLE
kable: Vertical page position with "valign" option does behave faulty

### ISSUE THREAD

**Issue by Seil85** [yihui/knitr#1487]
First, thank you for the great work!

I like to produce a floating table in `latex` with the `kable()`-function. Next to that I tried to figure out how the page position is set. There is an option 'valign' which comes from a hidden function `kable_latex` and is passed through when it is applied in `kable(dat,valign = "!b")`.

Producing a simple table we can do it like this:

```{r}
require(knitr)
dat <- data.frame(A=c(1,2,3,4),B=c(T,F))

kable(dat,format = "latex")
```
which will give the output as expected:
```
\begin{tabular}{r|l}
\hline
A & B\\
\hline
1 & TRUE\\
\hline
2 & FALSE\\
\hline
3 & TRUE\\
\hline
4 & FALSE\\
\hline
\end{tabular}
```
Putting a caption to the table, will generate a floating object with latex - `table` environment. But in case we like to have the table at the bottom of the page, which is usually done by `\begin{table}[!b]` the '[!b]' switch appears besides the ´tabular´ environment an NOT aside the ´table´. Proof:

R-code
```
require(knitr)
dat <- data.frame(A=c(1,2,3,4),B=c(T,F))

kable(dat,format = "latex",caption = "abc",valign = "!b")
```
And its output:
```
\begin{table} % <-- here [!b] is supposed to be

\caption{\label{tab:}abc}
\centering
\begin{tabular}[!b]{r|l}   %% here is the wrong position for [!b]
\hline
A & B\\
\hline
1 & TRUE\\
\hline
2 & FALSE\\
\hline
3 & TRUE\\
\hline
4 & FALSE\\
\hline
\end{tabular}
\end{table}
```
Since the functionality is given, but accidentally wrong composed, I would also suggest to document this option in the help of `kable` function.

**Comment by yihui** [comment]
That sounds like a bug to me. Are you able to fix it and submit a pull request?

**Comment by haozhu233** [comment]
@yihui I can help with this issue.

**Comment by yihui** [comment]
@haozhu233 Go ahead. I guess it is probably not hard.

**Comment by yihui** [comment]
Sorry but I just realized that I misunderstood it as I was looking at Table 2.3 in the **bookdown** book:

![image](https://user-images.githubusercontent.com/163582/64638834-35264380-d3cc-11e9-8c3c-23fcfa2abf8d.png)

The `valign` argument meant to control the vertical alignment of the `tabular` environment, instead of the floating position of the `table` environment. That means I was correct originally, and this issue was not a bug. I just reverted the PR #1519, and added a separate argument `position` for you to control the floating position instead (e.g., `position = "!b"`).
