### ISSUE TITLE
Exported alternative to knitr:::knit_code?

### ISSUE THREAD

**Issue by r-cheologist** [yihui/knitr#1545]
I'm using `knitr:::knit_code` in an RMD-processing documentation system and `R CMD check` obviously complains about that function not being exported ... is there a sane exported alternative?

Joh

**Comment by yihui** [comment]
No.

**Comment by r-cheologist** [comment]
Would you consider exporting it? Using it in a package and ':::' calls are frowned upon ...

**Comment by ProQuestionAsker** [comment]
Curious about the same thing. I'm working on a package (mostly for internal-team purposes) that would allow a user to export the code of specified (and varied) code chunks to an R script without knitting/executing the entire document. 

The only way I've found to do it is to use `knitr:::knit_code$get()` to expose the contents of each code chunk and programmatically filter them down to the ones that I actually want to export. I totally get not exporting a way to `set` chunk content since that could easily lead to some issues, but could there be an alternate that just `gets` existing content?

Also seems pretty similar to this old issue: https://github.com/yihui/knitr/issues/1026

**Comment by yihui** [comment]
Okay, I'll export it, and warn loud enough in the documentation :)

**Comment by yihui** [comment]
Done.

**Comment by ProQuestionAsker** [comment]
You are the best! Thank you! Promise we'll use it responsibly ;)

**Comment by r-cheologist** [comment]
Very, very nice! Thanks a bunch! Responsibly ( ;) ) using the reporting infrastructure needing this daily and can now avoid `R CMD check`'s complaints about `:::` usage ... thank you again.
