### ISSUE TITLE
fig.keep=3 suppresses code and output for markdown chunk

### ISSUE THREAD

**Issue by ajrgodfrey** [yihui/knitr#1579]
N.B. This was placed on Stack Overflow 24 hours ago.

I want to have only one plot generated by the following chunk. It currently generates two identical plots.

````
```{r addGridLines, fig.dim=c(6,6), fig.cap="Scatter plot of Ozone versus Wind with grid lines added.", fig.keep=3}
attach(airquality)
plot(Wind, Ozone, pch = 4)
abline(v=min(Wind)+c(0.25,0.5,0.75)*(max(Wind)-min(Wind)), col=6)
abline(h = min(Ozone, na.rm=TRUE) +c(0.25,0.5,0.75)*(max(Ozone, na.rm=TRUE)-min(Ozone, na.rm=TRUE)), col=6)
library(BrailleR)
WTF()
detach(airquality)
```
````

The library command is added here, but is in an earlier chunk in my document.

If I use the chunk argument fig.keep="first", then the scatter plot with no grid lines is generated. Using fig.keep="last" means the plot appears after the WTF() command. I know why this happens. I want the figure to appear before the library() command instead.

The WTF() command grabs the current graph window and re-creates the content using the grid system if it isn't in grid form already. In this case, the base graphics system is being used and so this chunk generates two graphs for me, both being given the same  caption.

My problem is that if I use fig.keep=3, I get the right graph, but none of the commands or the text output from WTF() are returned.

**Comment by dongzhuoer** [comment]
I suggest to change the title to 

> set `fig.keep` to numeric cause R code not echoed

**Comment by dongzhuoer** [comment]
And I want to add a reproduciable example here:

````rmd
---
output:
    html_document: default
    md_document:
        variant: markdown
---

# 1,2

```{r plot, fig.keep=c(1,2)}
plot(cars)
plot(sin, -pi, 2*pi) 
```

# 1

```{r plot, fig.keep=1}
```

# all

```{r plot, fig.keep='all'}
```

# first

```{r plot, fig.keep='first'}
```

# last

```{r plot, fig.keep='last'}
```


# none

```{r plot, fig.keep='none'}
```

````

**Comment by cderv** [comment]
For reference, the SO question is [this one](https://stackoverflow.com/questions/51530498/fig-keep-3-suppresses-echo-of-r-commands-and-results) and still has no answer.

**Comment by dongzhuoer** [comment]
The output is

![Uploading image.png…]()


You can see that all chunks except for the top two contain R code.

**Comment by cderv** [comment]
Coming back to this after some times. Thank you for the patience. 

There is indeed an issue when `fig.keep` is passed a numeric vector corresponding to all the plots (so equivalent to `"all"`). Currently I believe this line of code does not handle this case. 
https://github.com/yihui/knitr/blob/8d85e164f64518b254e4e0248635dbb9e4707f0d/R/block.R#L238

Here a reprex of what happens internally 
``` r
# which are figs in the result ?
res = c("source", "fig", "source", "fig")
figs = res == "fig"
# index of fig to keep. here 2 figures so we want all of them
keep.idx = c(1, 2)
# should keep all figures - but keep none because nothing to remove
-which(figs)[-keep.idx]
#> integer(0)
res[-which(figs)[-keep.idx]]
#> character(0)
```

So this case is not handle. It will even remove all the results that **knitr** should print.

When passing some numerics but less than available figures, it will work

See this examples: 
``` r
# we get not output
  xfun::raw_string(
    knitr::knit(text = "```{r plot, fig.keep=c(1,2,3)}
plot(1)         # high-level plot
abline(0, 1)    # low-level change
plot(rnorm(10)) # high-level plot
```"))

# we get the selected outputs
  xfun::raw_string(
    knitr::knit(text = "```{r plot, fig.keep=c(1,3)}
plot(1)         # high-level plot
abline(0, 1)    # low-level change
plot(rnorm(10)) # high-level plot
```"))
#> 
#> ```r
#> plot(1)         # high-level plot
#> ```
#> 
#> ![plot of chunk plot](figure/plot-1.png)
#> 
#> ```r
#> abline(0, 1)    # low-level change
#> plot(rnorm(10)) # high-level plot
#> ```
#> 
#> ![plot of chunk plot](figure/plot-2.png)
```

This explains the issue found by @dongzhuoer. 

I believe the first issue reported by @ajrgodfrey is expected as you are only asking to keep the 3 figures (including low level) so the one after the second `abline()`. If `WTF()` output a figure it will indeed be removed. 
I am not sure what is the expected output because **BrailleR** package seems to show the previous plots in duplicates. Sorry.
