### ISSUE TITLE
Creating knit_print.foo method does not work in R 3.5

### ISSUE THREAD

**Issue by wch** [yihui/knitr#1580]
Example:

    ---
    output: html_document
    ---
    
    ```{r}
    knit_print.data.frame <- function(x, ...) {
      cat("HELLO!")
    }
    
    pressure
    ```
    

In R 3.4.4 (on rstudio.cloud), I get this:

![image](https://user-images.githubusercontent.com/86978/43348995-9391c7b6-91c2-11e8-9ce9-7bcb71544085.png)

In R 3.5.0 (on rstudio.cloud and on my local mac), I get:

![image](https://user-images.githubusercontent.com/86978/43349014-adb62d80-91c2-11e8-81d8-13e1131c4a4f.png)

I believe it must be due to a change in how S3 dispatch works.

A workaround is to use `registerS3method`.

Here's an example that prints some more information and uses `registerS3method`.

    ---
    output: html_document
    ---
    
    ```{r}
    library(knitr)
    knit_print.data.frame <- function(x, ...) {
      cat("HELLO!")
    }
    
    registerS3method("knit_print", "data.frame", function(x, ...) {
        cat("HELLO 2!")
    })

    methods("knit_print")
    getS3method("knit_print", "data.frame")
    pressure
    ```
    

R 3.4.4:

![image](https://user-images.githubusercontent.com/86978/43349104-1f8542ca-91c3-11e8-878b-63ea564af5fc.png)

R 3.5.0:
![image](https://user-images.githubusercontent.com/86978/43349092-112cd71a-91c3-11e8-907e-6e2a589e9314.png)

**Comment by yihui** [comment]
Thanks for the report! I was aware of it when R 3.5.0 was released, but haven't had a chance to investigate it. I think you are correct that the S3 dispatch mechanism has changed somehow.

**Comment by kevinushey** [comment]
We had to make a number of changes in RStudio to accommodate this:

https://github.com/rstudio/rstudio/pull/2762

Not sure if it's helpful here, but our (very gross) workaround was to patch the S3 methods table directly:

https://github.com/rstudio/rstudio/pull/2762/files#diff-70c773ec78a4d2867262228e1bbaf1c7R377

**Comment by wch** [comment]
Yuck, that's unfortunate that there's no way to easily add a temporary S3 method now.

**Comment by skranz** [comment]
Just for info: I encountered a variant of this problem. My custom `knit_print.data.frame` function works if no package is loaded that also implements that function. Yet, if I load the package `rmarkdown`, which implements a `knit_print.data.frame` function, my custom function does no longer work, however.

Below is an example code. It can also be tested [https://rstudio.cloud/project/137636](https://rstudio.cloud/project/137636) 

```r
# Restart R session if you load / unload rmarkdown

# Custom knit_print.data.frame only works if rmarkdown is not loaded
# library(rmarkdown) 
library(knitr)

knit_print.data.frame = function (x, options = NULL, ...) {
  asis_output("Custom Data Frame Printer!")
}

txt = "
```{r}
data.frame(x=1,y=2)
```"
html = knit2html(text=txt,fragment.only=TRUE)
html
```
The work around with `registerS3method` seems to work, however. Maybe one could update the vignette [https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html](https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html) and note this workaround?

**Comment by yihui** [comment]
Yes, I should definitely update the vignette, and I need some helping hands...

**Comment by skranz** [comment]
I don't know whether that counts as a helping hand. But until some other resolution is found, you could e.g. just change lines 40-50 in [https://github.com/yihui/knitr/blob/master/vignettes/knit_print.Rmd](https://github.com/yihui/knitr/blob/master/vignettes/knit_print.Rmd) by the following new lines. Note that if `rmarkdown` is loaded, I needed to register additionally for the class `grouped_df`, even though grouped tibbles also have the class `data.frame`.

---

S3 generic functions are extensible in the sense that we can define custom methods for them. A method `knit_print.foo()` will be applied to the object that has the class `foo`.

Here is quick example of how we can print data frames as tables:

```{r}
library(knitr)
# define a method for objects of the class data.frame
knit_print.data.frame = function(x, ...) {
  res = paste(c('', '', kable(x)), collapse = '\n')
  asis_output(res)
}
# Also call registerS3method to make sure that knitr finds the custom method 
registerS3method("knit_print", "data.frame", knit_print.data.frame)
registerS3method("knit_print", "grouped_df", knit_print.data.frame)
```
The calls to `registerS3methods` are a workaround for some problems due to recent changes in the S3 dispatch mechanism. Without those calls, knitr may not always find your custom method, depending on which other packages you have loaded. See the discussion in this Github issue: https://github.com/yihui/knitr/issues/1580

**Comment by yihui** [comment]
Thanks @skranz! That was helpful. I just clarified in the vignette that `registerS3method()` would be necessary for methods defined in code chunks, and pointed package authors to https://github.com/rstudio/htmltools/pull/108 if they don't want to import **knitr** but keep it as a Suggests dependency.
