### ISSUE TITLE
Possible bug in knitr::opts_knit$set

### ISSUE THREAD

**Issue by arnonl** [yihui/knitr#1603]
Dear Yihui,

In the attached code below, the first plot is red while the second is black even though I'm using the global.par = TRUE .

Any error on my side?
(I'm using knitr 1.2 and R version 3.5.0)

````
---
title: "Global.par error"
date: "9/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(global.par = TRUE)
```

```{r plotA, echo=FALSE}
par(col = "red")
with(mtcars, plot(qsec, disp))
```

```{r plotB, echo=FALSE}
with(mtcars, plot(qsec, disp))
```

````

Thank you!

**Comment by yihui** [comment]
Hint: read your subject and the first line of code in your Rmd again, and compare the things after `::` a little more carefully :)

Please read the issue template carefully the next time you file an issue to make sure your issue is correct formatted (in particular, please check out [the four-backtick rule](https://yihui.name/en/2017/05/four-backticks-github/)).

**Comment by yihui** [comment]
Much appreciated for the edit!

Now I can easily reproduce your issue. That is really odd. I cannot think of a reason why it would fail. I tried `par(bg = 'red')` and it worked. It seems only `col` fails. I don't know why, and don't have time to debug it. If you want to debug it by yourself, here is the relevant source code:
https://github.com/yihui/knitr/blob/4cf7a6f1ef3e083464823a15921385a452177412/R/block.R#L134-L141

**Comment by arnonl** [comment]
Dear Yihui,
Thank you for taking the time to look at my code and for the link. Unfortunately it beyond my programing skills.  Actually it seems like it an even more serious bug than what we thought... watch this:

Run this in a normal console:
```
par(mfrow=c(1,2))
par(col='red')
old_par <- par()
old_par$col; old_par$mfrow
```
The output is as expected...

Than, try it within a Rmarkdown file:
````
```{r eval=TRUE}
  par(mfrow=c(1,2))
  par(col='red')
# Save the graphical parameters so it can be used later
  old_par <- par()
  old_par$col; old_par$mfrow
```
````
When you run the whole chunk at once, you get the right output.
However, if you run it line by line with command-ENTER you get the wrong answer!... Did I miss something?

Thank you!

**Comment by yihui** [comment]
I think that is a different story (related and specific to RStudio). It is probably not related to your original issue.

**Comment by arnonl** [comment]
Yes, you're right. I will try to post it there. Thank you. Do you want me to close this issue?

**Comment by yihui** [comment]
Please feel free to leave it open, in case someone else with enough debugging skills can figure it out. Thank you!

**Comment by RolandASc** [comment]
it would also be an issue like this:

```r
par(col = "red")
with(mtcars, plot(qsec, disp))
# below is essentially what is happening in knitr
par(par(no.readonly = TRUE))
with(mtcars, plot(qsec, disp))
```

I believe the problem is with `fg` overwriting `col`. See `?par`.

Flipping the order would work, but that doesn't seem like a satisfactory solution ;)
```r
par(rev(par(no.readonly = TRUE)))
```

**Comment by yihui** [comment]
@RolandASc What a great detective you are! 👍

**Comment by cderv** [comment]
Coming back to this. Look at the documentation of `?par` it seems some parameters have this kind of special dependency when sets in `par()` : 
* `fg` will also set `col` 
* `bg` will set `new = FALSE`
* `mfcol` or `mfrow` would reset `cex` and `mex` to 1
* `tcl = NA` will set `tck = -0.01`

Maybe a strategy would be to only deal with what is reported because it is not easy to handle and be sure of all case. 

If `rev()` is not the best option, the idea could be the same: We use a `knitr:::par2()` internal wrapper of `par()` to handle some special case. We could definitely handle `fg` and `col` by only changing the order of those two to apply col after `fg` - I think it should do the trick
