### ISSUE TITLE
Unwanted rounding of tibbles when knit to Word or PDF but not HTML

### ISSUE THREAD

**Issue by Aariq** [yihui/knitr#1606]
When tibbles are knit to Word or pdf some numbers get rounded so there is a decimal point printed but no digits after it.  I've provided a reproducible example.  It seems to only affect numbers with a certain number of digits.

when knit, this output appears as expected:

```{r}
data.frame(x = c(3.3, 32.6, 160.2, 1546.6)) 
```

If I do the same thing but with `data_frame`, then row 1 and 2 appear as expected but row 3 displays as `160. ` and row 4 appears as `1547. ` when knit to Word or pdf (but not HTML).

```{r}
data_frame(x = c(3.3, 32.6, 160.2, 1546.6)) 
```
<img width="555" alt="screen shot 2018-09-18 at 10 10 19 am" src="https://user-images.githubusercontent.com/25404783/45693438-20053480-bb2b-11e8-99a7-d30923b38d70.png">

System info:
R version 3.5.1 (2018-07-02)
R Studio Version 1.1.456
tibble version 1.4.2
knitr version 1.20

**Comment by riinuots** [comment]
I just came across this as well.
For me, it's not output dependent: both HTML and PDF start taking away decimal places from the tibble if the number has more than 3 significant figures (knitr version 1.23). I think it's helpful in many cases - to reduce the number of decimal places and get a nicer printout. But I wish it would match the precision for all values within the same column.
**Anyway, workaround/fix:**
Include e.g.,  `options(pillar.sigfig = 5)` to increase the number of significant figures that get included.

**Comment by cderv** [comment]
Hi thanks for the report. 

This issue is not knitr related, this is the way it works with `tibble` 📦 
``` r
library(tibble)
packageVersion("tibble")
#> [1] '2.1.3'

data.frame(x = c(3.3, 32.6, 160.2, 1546.6)) 
#>        x
#> 1    3.3
#> 2   32.6
#> 3  160.2
#> 4 1546.6
data_frame(x = c(3.3, 32.6, 160.2, 1546.6)) 
#> Warning: `data_frame()` is deprecated, use `tibble()`.
#> This warning is displayed once per session.
#> # A tibble: 4 x 1
#>        x
#>    <dbl>
#> 1    3.3
#> 2   32.6
#> 3  160. 
#> 4 1547.
options(pillar.sigfig = 5)
data_frame(x = c(3.3, 32.6, 160.2, 1546.6)) 
#> # A tibble: 4 x 1
#>        x
#>    <dbl>
#> 1    3.3
#> 2   32.6
#> 3  160.2
#> 4 1546.6
```

<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You need to change the option if you want a different printing as @riinuots said.
This is explained in the printing documentation of tibble
https://tibble.tidyverse.org/reference/formatting.html

In knitr, you'll get the same result as in R if you don't use a specific table format. You can use `kable` to get a table output for you desired format. 
``` r
knitr::kable(tibble::data_frame(x = c(3.3, 32.6, 160.2, 1546.6)))
#> Warning: `data_frame()` is deprecated, use `tibble()`.
#> This warning is displayed once per session.
```

<table>
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3.3</td>
</tr>
<tr class="even">
<td style="text-align: right;">32.6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">160.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">1546.6</td>
</tr>
</tbody>
</table>

<sup>Created on 2019-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
