### ISSUE TITLE
include page_num argument in knitr::include_graphics 

### ISSUE THREAD

**Issue by randomgambit** [yihui/knitr#1612]
Hello there,

This is related to https://stackoverflow.com/questions/52486342/how-to-add-a-multipage-pdf-to-rmarkdown

In would be nice to add a `page_num` argument in `include_graphics` so that people can iterate over the pages in a given pdf. Right now, the only possibility is to show the first page which is a bit arbitrary.

What do you think?
Thanks!

**Comment by cderv** [comment]
Thanks for sharing this @randomgambit ! 

The answer to the question (https://stackoverflow.com/a/52494352/3436535) mentions options that could be passed to `\includegraphics`

This command as a `page` option that could be used to select the page of a multi page pdf
https://latexref.xyz/_005cincludegraphics.html

Currently this cannot be done using `knitr::include_graphic()` but it can be done using `out.extra`

````markdown
---
title: "crazy test"
output:
  pdf_document:
    keep_tex: TRUE
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h')
```


```{r, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(purrr)

mydata <- tibble(group = c('a', 'a', 'a', 'b', 'b', 'b'),
                     x = c(1,2,3,5,6,7),
                     y = c(3,5,6,4,3,2))

mydata2 <- mydata %>% group_by(group) %>% 
  nest() %>% 
  mutate(myplot = map(data, ~ggplot(data = .x, aes(x = x, y = x)) + geom_point()))

pdf("mychart.pdf")
print(mydata2$myplot)
dev.off()
```

Only first page

```{r label, out.width = "85%", fig.cap = "caption"}
knitr::include_graphics(path = "mychart.pdf")
```

second page

```{r label2, out.width = "85%", fig.cap = "caption", out.extra=c"page=2")}
knitr::include_graphics(path = "mychart.pdf")
```
````

`knitr::include_graphics()` does not handle any option for any format, so I am not sure that it could support this specific option. Moreover, `out.extra` is more generic as it will apply to all type of content not just `knitr::include_graphics`. 

However, it is worth thinking about it as I see why it make more sense to pass option using this function rather than chunk option.
