### ISSUE TITLE
Is it possible to add cache for in-line codes?

### ISSUE THREAD

**Issue by Sciurus365** [yihui/knitr#1617]
Hello,
Recently I using `knitr` to write .Rnw dynamic documents. In my file, I have to do many in-line model fittings, which is quite time-consuming. I found cache can only be used in chunks, but in-line codes cannot be cached in the default setting. Is it possible to add the cache for in-line codes? If not, would you please add this feature in future releases?
Thank you!

**Comment by yihui** [comment]
Sorry, but I'm not interested in implementing this feature. On one hand, it is tricky because inline expressions don't have labels (IDs) like code chunks. On the other hand, the workaround is too straightforward: just do the time-consuming computing in code chunks (with `cache=TRUE`), and use inline expressions only for displaying values.

In conclusion, it is something that appears to be easy for you but hard for me, so I tend not to do it. Thanks for the suggestion anyway!
