### ISSUE TITLE
Bug: numbers in tables that are less than 1e-7 appear as 0, when thrown to kable()

### ISSUE THREAD

**Issue by gautig** [yihui/knitr#1664]
I would think that this bug is easy to reproduce. Say you have a small data.frame called results, which looks like this:
```
                         term        HR    HR_low   HR_high      p.value
1 Any_autoimmune_disease_case 0.7422095 0.6675966 0.8251614 3.485583e-08
```

The value in column p.value is < 1e-7.

Do the following in R.

```{r}
kable(results)
```
The output is then:
````
term HR HR_low HR_high p.value
Any_autoimmune_disease_case 0.7656125 0.6968154 0.8412020 0
````
See, the value in column p.value is displayed a 0.

**Comment by yutannihilation** [comment]
This is because numeric values are `round()`ed. As documented, you can pass `digits` argument if you need more digits than the value of your `getOption("digits")`.

https://github.com/yihui/knitr/blob/2814058da5f83941862813928e78e79245fdc93d/R/table.R#L16-L18

``` r
knitr::kable(3.485583e-08)
```

<table>
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>

``` r

knitr::kable(3.485583e-08, digits = 10)
```

<table>
<thead>
<tr class="header">
<th style="text-align: right;">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3.49e-08</td>
</tr>
</tbody>
</table>

<sup>Created on 2019-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by gautig** [comment]
Thank you very much! ☺
