### ISSUE TITLE
A hook before processing the document / text?

### ISSUE THREAD

**Issue by NMarkgraf** [yihui/knitr#1707]
Hi!

May it be possible to implement a hook right before processing the whole document. Quasi a preprocessor-hook?

Maybe right before calling `process_file()` in the main `knitr()` function. Just sending the whole text to a function which is a hook and normally return the text identically, but with the possibility to change the text? Just like the document hook does it after processing?

Why? - Well, it would make preprocessing possible, which you be a great thing I guess.

Yours
Norman

**Comment by yihui** [comment]
The problem is that you cannot set such a hook inside a source document (in a code chunk), because it would be too late for this hook to execute. You will have to set it before `knit()` starts. I don't know how useful it could be practically. I mean when you compare

```r
knitr::knit_hooks$set(before_knit = function() ...)
knitr::knit('foo.Rmd')
```

with

```r
pre_process(readLines('foo.Rmd'))
knitr::knit('foo.Rmd')
```

I don't feel there is obvious advantage of the former approach. The latter approach doesn't need my support---you are free to pre-process your document with any function.

**Comment by NMarkgraf** [comment]
Well, if you have not only ONE document, but many child documents there is a tiny advantage, such as you don't have to scan all (child-)documents but only the generated by kntir one. -- But okay.
