### ISSUE TITLE
New width behaviour (version 1.26) invalidates cache

### ISSUE THREAD

**Issue by jaburgoyne** [yihui/knitr#1781]
This point is too general to warrant a specific example; rather it is a major effect of the 'minor' change in v. 1.26 with respect to the global `width` option. 

The `width` option is part of the MD5 sum for (in)validating the **knitr** cache, and thus any time users change the `width` option (e.g., to look at a particularly large nibble) and re-knit, they have -- probably inadvertently! -- invalidated their entire cache. This is a very easy mistake to make when working under Emacs/ESS instead of RStudio, and if there was a good reason to use caching, it is unfortunately also a very costly mistake.

Although it is always possible to work around this behaviour by setting `width` manually in a setup chunk, it feels like a dangerous 'gotcha', even for advanced users. Would it be possible to add the global `width` option to `knitr:::cache1.opts` somehow? That seems like it would fit the spirit of how `cache = 1` and `cache = 2` are intended to work.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by yihui** [comment]
Thanks for the report! I became aware of this issue right after I released 1.26. After some more thinking, I decided that `options('width')` should not be taken into consideration when calculating the MD5 sum. As you said, it is too costly for users to invalidate their cache (inadvertently) due to changes in a cosmetic option (i.e. `width`).

Unfortunately this means your cache will be invalidated again after the next version of **knitr** is released (apologies!), but hopefully it will be stabler in the future.
