### ISSUE TITLE
file("") only supports open = "w+" and open = "w+b"

### ISSUE THREAD

**Issue by Wanqi-Wang** [yihui/knitr#1818]
Hello, i have a question when use spin() function

i write the code according to the guide, like this
```{r}
library(knitr)
(s = system.file("w2 note", "knitr-spin.R", package = "knitr"))
spin(s)
```
"w2 note" is the r script I want to convert to html
however, it show me that 
```{r}
Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former
```

why does it happen, what should I do?

Thanks,
Wanqi

**Comment by malcolmbarrett** [comment]
`spin()`'s first argument should be a path to an R file to spin. You might have noticed that `(s = system.file("w2 note", "knitr-spin.R", package = "knitr"))` printed out `""`; this is because `system.file()` is actually for accessing files from R packages. So the guide you used called `system.file("examples", "knitr-spin.R", package = "knitr")` to get the path to this file in the knitr package. Because there's no file at `system.file("w2 note", "knitr-spin.R", package = "knitr")`, you ended up running `spin("")`.

So, the answer is simple: run `spin("w2 note.R")` or whatever the name of your `.R` file is.

Also, GitHub repositories are generally not the best places to ask these sorts of questions; they are better for bug reports and feature requests. Next time, try [RStudio Community](https://community.rstudio.com/) or maybe [StackOverflow](https://stackoverflow.com/). I believe this repository has an issue template that mentioned that.

**Comment by Wanqi-Wang** [comment]
> spin()'s first argument should be a path to an R file to spin. You might have noticed that (s = system.file("w2 note", "knitr-spin.R", package = "knitr")) printed out ""; this is because system.file() is actually for accessing files from R packages. So the guide you used called system.file("examples", "knitr-spin.R", package = "knitr") to get the path to this file in the knitr package. Because there's no file at system.file("w2 note", "knitr-spin.R", package = "knitr"), you ended up running spin("").
> So, the answer is simple: run spin("w2 note.R") or whatever the name of your .R file is.
> Also, GitHub repositories are generally not the best places to ask these sorts of questions; they are better for bug reports and feature requests. Next time, try RStudio Community or maybe StackOverflow. I believe this repository has an issue template that mentioned that.

Thank you very much, and then I try this code
```{r}
spin("w2 note.R")
```
and
```{r}
spin("w2 note.R", knit = FALSE,format = "Rmd")
```
it shows me it:
```{r}
> spin("w2 note.R", knit = FALSE,format = "Rmd")
Error in parse(text = x, keep.source = TRUE) : 
  <text>:106:8: unexpected symbol
105: 
106: create folder
            ^
```
and I am so confused.
Thanks again! 😺

**Comment by shrektan** [comment]
If you are on Windows, please make sure that your "w2 note.R" is UTF-8 encoded. In addition, I suggest you remove the space " " in your R script's file name, which may irrelevant but it's always a good thing to do.

**Comment by yihui** [comment]
@Wanqi-Wang The error message indicates that your R script is not syntactically valid; `create folder` is not valid R code. The issue guide asked for a reproducible example, which you didn't provide, so we are unable to offer further help.

**Comment by malcolmbarrett** [comment]
Thanks, Yihui. 

@Wanqi-Wang, if you're still having issues, this is a good time to try RStudio Community, where this type of question fits better. Feel free to post a question with a bit more detail and tag me (my username is `@malcolm`) and I or others will help you. As Yihui mentioned, it's important you post enough details that we can help. See http://tidyverse.org/help for some examples.

**Comment by Wanqi-Wang** [comment]
Thanks! These solutions are helpful!  by encoding the file. I am a new beginner, and I just realized it's suitable to ask question at Rstudio community and StackOverflow😸. Sorry about this and thank you all for passion and help!!! ☕️ 🌷
