### ISSUE TITLE
\newpage does not work properly to generate word doc

### ISSUE THREAD

**Issue by HaoLi111** [yihui/knitr#1844]
```{r cars}
plot(cars)
```
\newpage
balabala

will work for pdf but not for word. On the word doc, it does not start a new page

```
R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
```

**Comment by cderv** [comment]
This pagebreak feature is not a knitr feature but an Rmarkdown feature since rmarkdown 1.16
https://rmarkdown.rstudio.com/docs/news/index.html#rmarkdown-1-16-2019-10-01

You need to check your rmarkdown version. This should work:
````md
---
title: test
output: word_document
--- 

```{r}
plot(cars)
```

\newpage

balabala
````

I'll close this. If you still have an issue about this, please fill in Rmarkdown repo following the issue template. Thank you.
