### ISSUE TITLE
mclapply and knitr/pandoc

### ISSUE THREAD

**Issue by ekianjo** [yihui/knitr#1848]
I have been looking around in SO and RStudio community forums but I cannot find any answer to this topic. I am using mclapply (parallel package) to run several threads of rmarkdown::render in parallel. On my local machine it works fine with 2 cores/threads, while it fails for no apparent reason (one thread refuses to execute the render while the other does, so 1/2 is done in the end) on a remote server. Pandoc version is not the issue as I use up to date pandoc in both cases. R version is 3.4.4 on the remote server and 3.6.3 on my local machine. 

The pandoc error is simply "pandoc conversion failed with error 1" with no further details. On the remote server if I run with a single core instead of 2, it works fine (but not in parallel anymore).

Would anyone have a hint as to where I could start debugging this?

**Comment by cderv** [comment]
> I have been looking around in SO and RStudio community forums but I cannot find any answer to this topic.

Have you asked on those forums, [as the issue guide suggests](https://yihui.org/issue/#got-a-question) ? There could be someone that have tried to do the same in the community. 

There is a lot that could be going one in your case between your setup and the specific way you have to run your code. Without any example to reproduce, it is difficult to help. We can only "guess" the details on your implementation. 

If you have a pandoc error and not an R error during knitr rendering, this could mean this is the conversion by pandoc that failed. It think pandoc add a message just before the error, something like 
```sh
/usr/local/bin/pandoc +RTS -K512m -RTS Untitled.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output Untitled.pdf --template /Users/jracine/Library/R/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --pdf-engine /opt/local/bin/pdflatex --variable graphics=yes --variable 'geometry:margin=1in' 
pdf-engine /opt/local/bin/pdflatex is not compatible with output format latex
Error: pandoc document conversion failed with error 1
Execution halted
```
Check if you have something. 
Also, you need to check all files are accessible, with no conflict between the two processes on the files you are rendering, and where you are rendering. You need to understand correctly how path are dealt with using knitr and rmarkdown so that it works as expected on a remote server. 

I would advice to ask on the community, to see if someone has an experience with this. If you manage to create a reproducible example, and find an issue in knitr or rmarkdown, please open it with details. 

Thank you!

**Comment by ekianjo** [comment]
Hi @cderv for your answer. I currently do not have a reproducible piece of code since this issue is only found on the remote server and nowhere else I could try the code on so far, which is also why I am at a loss and decided to resort to ask around here.

As to the pandoc error, there are no useful clues in the log apart from what I shared, since i run a command line knitr command thru a Rscript and apparently pandoc does not return complete logs in such cases (unless I am missing a way to do that?)

Note that pandoc works fine in single-core setting, so it's only an issue that occurs on the remote server when multi-cores are running pandoc at the same time. 

I have tried to give additional parameters to knitr to get around this issue as I imagined that having all intermediate files written in the same folder may cause issues - I therefore created unique temporary directories for every time pandoc is called for a safer behavior, however that did not fix the problem at all so I am guessing this is not file conflict either.

One question, would the rmarkdown::render "env= new.env()" parameter do anything in this kind of situation? Or completely unrelated?

**Comment by ekianjo** [comment]
I forgot to mention that I am generating html reports with pandoc, not pdf, if that even matters.

**Comment by cderv** [comment]
It is really difficult for us to do something about a non reproducible issue, as it is only you specific remote server. The issue needs to be isolated - is it an error with rmarkdown, with knitr, with pandoc, or even with way you parallelise ? 

At least if you provide an example I can try to run on my side, I could have a look. Otherwise, you need to dig on your own and share your findings in due time I guess.

**Comment by cderv** [comment]
And it seems parallelized rendering works for some R user : https://gist.github.com/hrbrmstr/17bc21af55392f23f012f57bb2fda51c. You may try this approach.

**Comment by ekianjo** [comment]
@cderv I have no problem with parallelized rendering on several local machines I tried, as I mentioned before. My issue is that it does not work for some unknown reason on that particular remote server, but I do not have any helpful error message so far. Anything I can do to make pandoc writer longer logs when rendering?

**Comment by atusy** [comment]
@ekianjo
I'd suggest `mclapply` pandoc via `system` function. In this way, you will see if the trouble is related to rmarkdown or the others (`mclapply`, pandoc, ...)

**Comment by ekianjo** [comment]
@atusy can you explain in more details what you mean by "via the system function"? you mean system("pandoc + all arguments") ?

**Comment by atusy** [comment]
@ekianjo yes. that's what i meant. of course you can try variety of arguments to see difference.

**Comment by ekianjo** [comment]
@atusy in order to that I need to first generated the .Rmd files as a first step, and then run pandoc on the .Rmd files afterwards, correct?

**Comment by atusy** [comment]
You can locally `keep_md` the md files and required files, upload them to your server, and run pandoc in parallel. You should also check if sequential executions of pandoc fail or not.

**Comment by ekianjo** [comment]
thanks, let me try that -

**Comment by cderv** [comment]
@ekianjo As you did not came back with more question, I'll consider this one closed. 

If you still have question on how to run in parallel this kind of task, please ask a question on the Q&A forum ? https://yihui.org/issue/#got-a-question

Thank you !
