### ISSUE TITLE
Suggestion:  export `knitr:::wrap`

### ISSUE THREAD

**Issue by dmurdoch** [yihui/knitr#1853]
In #1852, I described trouble creating a `knit_print` method for the result of `rglwidget()`, because it's an `htmlwidget` descendant, and they are handled by the generic `knit_print` method, rather than delegating to a method.  In the meantime, I think I've found a better solution to the underlying problem, but this solution requires use of the internal function `knitr:::wrap`, so I am suggesting `wrap` should be exported.

Here is the issue:  I would like `rgl` outputs to be automatically included in `knitr` documents, using the same rules as standard R graphics, i.e. respecting the different settings for `fig.keep` in the chunk options.  With the current `knitr` code, I believe the following is a description of how graphics are normally included:

- all graphics operations (both low level and high level) result in `grDevices::recordPlot` being called to record the plot state.   These are stored in a list with the echoed R code, text output, etc., in objects with class `"recordedplot"`.
- after fully processing the code chunk, `knitr` goes through the list and removes things that shouldn't be displayed. 
- It then calls the internal `wrap()` on the remaining items to produce the final text to include in the output. 

So if I have `fig.keep = "high"` (the default), the intermediate low level plot changes are removed in the second step, and `wrap()` is only called after the last change to each plot.

I can mimic this in `rgl` by having a `knit_print` method that creates an object descending from `"recordedplot"` but containing data that can be turned into an `rglwidget()` result.  However, if I don't have a `wrap()` method for my object, the standard one will be called and will give an error because my object can't be replayed the way a standard `"recordplot"` object can.  So I need a `wrap()` method, which is problematic because `wrap()` is not exported.  I can still create it using undocumented tricks, but it's bad practice to use package internals, and CRAN would justifiably reject the change.

Here's my current code to implement this, which appears to work, but uses `knitr:::wrap`:

```
knit_print.rglId <- local({
  plotnum <- 0
  function(x, options, ...) {
    if (getOption("rgl.printRglwidget", FALSE))	{
      scene <- scene3d()
      args <- list(...)
      if (inherits(x, "rglHighlevel"))
        plotnum <<- plotnum + 1
      structure(list(plotnum,  # knitr uses this to decide whether to suppress the plot
                     scene = scene,
                     width = figWidth(),
                     height = figHeight(),
                     options = options, args = args),
                class = c("rglRecordedplot", "recordedplot"))  
    }
  }
})

wrap.rglRecordedplot <- function(x, options = list(), ...) {
  widget <- rglwidget(x$scene, 
                      width = x$width,
                      height = x$height,
                      reuse = TRUE)
  knitr:::wrap(do.call("knit_print", c(list(widget, x$options), x$args)),
               options, ...)
}

setupKnitr <- function() {
  # R produces multiple vignettes in the same session.
  environment(rglwidget)$reuseDF <- NULL

  if (requireNamespace("knitr")) {
    options(rgl.printRglwidget = TRUE, rgl.useNULL = TRUE)
    registerS3method("wrap", "rglRecordedplot", wrap.rglRecordedplot, environment(knitr::knit_print))
  }
}

```

**Comment by cderv** [comment]
Hi, 

In order to better understand what you want to do, can you provide a reproducible example of your use of `rglwidget()` and what does not work ? 

Specifically, I am interested to understand how it plays and/or differs with the knitr support already availabe in `rgl` 📦 . Like `?rgl::hook_rgl`
Also, the package have already a `rgl:::knit_print.rglId` and `rgl::setupKnitr` function - So I am guessing you want to superseed those ? 

Regarding the solution of exporting `knitr:::wrap`, see also previous comment https://github.com/yihui/knitr/pull/1799#issuecomment-577220774. If we can understand more precisely your need, it would help answer with the best approach. 

Thank you !

**Comment by dmurdoch** [comment]
The problem I am trying to solve is to support `fig.keep` in `rgl`.  For example, this chunk only shows two plots:

``````
```{r fig.keep="high"}
plot(1:10, 1:10)
abline(h = 5)
plot(1:5, 1:5)
abline(h = 5)
```
``````

and they are displayed after the `abline()` calls.  I'd like the same sort of behaviour in this `rgl` version:

``````
```{r fig.keep="high"}
library(rgl)
setupKnitr()
plot3d(1:10, 1:10, 1:10)
planes3d(0, 0, 1, -4)
plot3d(1:5, 1:5, 1:5)
planes3d(0, 0, 1, -4)
```
``````

Currently I have to explicitly say where the plots should be inserted, using calls to `rglwidget()`:

``````
```{r}
library(rgl)
plot3d(1:10, 1:10, 1:10)
planes3d(0, 0, 1, -4)
rglwidget()
plot3d(1:5, 1:5, 1:5)
planes3d(0, 0, 1, -4)
rglwidget()
```
``````

I'd like to have `knitr` automatically decide where to do the displays, the way it can with standard graphics.  

This change would also allow `fig.show` and `fig.beforecode` to work for `rgl` graphics as well, without any additional work.  Those are quite tricky to do using just `rglwidget()` calls:  to implement `fig.show="hold"`, I'd need something ugly like

``````
```{r echo = c(1:3, 5:6)}
library(rgl)
plot3d(1:10, 1:10, 1:10)
planes3d(0, 0, 1, -4)
x1 <- scene3d()
plot3d(1:5, 1:5, 1:5)
planes3d(0, 0, 1, -4)
x2 <- scene3d()
rglwidget(x1)
rglwidget(x2)
```
``````

and `fig.beforecode = TRUE` would be even worse.

**Comment by dmurdoch** [comment]
Okay, it looks like I have a workaround that lets me get what I want.  I copy a big section of `knitr:::block_exec` into a chunk hook in rgl, and do the processing of `fig.keep`, `fig.show`, and `fig.beforecode` myself.

**Comment by dmurdoch** [comment]
Actually, this doesn't appear to be possible.  The trouble is that `wrap()` sets `fig.num` and `fig.cur`, but these need to be set after the culling of hidden figures takes place, or the numbering is off.

**Comment by dmurdoch** [comment]
I have a new workaround, using the undocumented `evaluate` hook.  I run the old `evaluate` code, then mess around with the list that's returned.  It's more reliable than working with the chunk hook, and it's CRAN-legal because it doesn't use any non-exported functions.  On the other hand, it's not nearly as simple as the code that uses `wrap`, so it's probably less robust against changes in `knitr`.

**Comment by burchill** [comment]
Can you explain what you did?  I'm in a similar boat (I got here by finding #1852 ) where I'm making a `knit_print` function for a descendent of `htmlwidget`, and I don't get the chance to change the `screenshot.force` option.

What you're talking about with these workarounds seems incredibly hacky to me.  It would make much more sense (in my mind) to have the ability to do something like this, which just turns off the `needs_screenshot()` necessity.

```r
knit_print.plotly <- function(x, options, ...) {
  options$screenshot.force <- FALSE
  knitr::knit_print(plot_plotly(x), options=options, ...)
}
```

Is there an important reason why `knitr` checks to see if an object needs a screenshot before actually going in to the `knit_print` methods that users can actually modify?  This hardline approach doesn't make sense to me---why wouldn't it make more sense to 1) move the `needs_screenshot()` check to `knit_print.default` or make `knit_print` functions for the three types of objects that trigger the screenshots ('htmlwidget', 'shiny.appobj', and 'knit_embed_url'), rather than running rampant over the users' customizations?

If it's just an oversight, I could probably make a pull request and move the `if (need_screenshot(x, ...)) html_screenshot(x)` bit of `knit_print` to `knit_print.default()`, where (I think) it more rightly belongs.

**Comment by dmurdoch** [comment]
Yes, what I did is quite hacky.  Here's an overview; if you want to see the actual code, it's here: https://github.com/rforge/rgl/blob/a6826a66ce75696d24c47122d1f1e3f9f68e5bed/pkg/rgl/R/Sweave_knitr.R#L302 .

The idea works with the `knitr::block_exec` function, which is the main function for evaluating code chunks. Skipping lots of details and exceptions depending on chunk options, it breaks up the code into top-level expressions, and evaluates all of them, saving the results before auto-printing (plus errors, etc.) in a list.  This is done by the `"evaluate"` hook.  Then it deletes some, and rearranges them, and calls the internal `wrap()` function, which calls `knit_print` and other things to produce the actual output.

My hacky solution installs an `"evaluate"` hook,  which calls the original one, then does the 
necessary rearrangements, and converts `rgl` output into something that won't be messed up by the code at the beginning of the `knit_print` generic.  It modifies the chunk options so that when `block_exec()` does its own rearrangements, it leaves everything alone.  

This could be a lot less hacky if I could install methods for the `wrap()` function.  I can make the output of `rgl` functions look like what you get from printed graphics so that `block_exec()` does all the requested rearrangements, then in `wrap()` handle them appropriately.  I suspect your patch in #1860 would also let me do what I want.

**Comment by dmurdoch** [comment]
Just one thing to add:  after thinking about it a bit more, I think my changes would need one other thing besides your patch in order to be less hacky.  If `knitr` could add a name to the list of classes it uses to detect that something is a plot subject to `figure.keep` and related chunk options (currently it has hard coded the classes `"knit_image_paths"` and `"recordedplot"`), then I could add that class, and things would just work.

**Comment by burchill** [comment]
Have you thought about setting the `render` chunk option globally to a function that checks if the object about to be `knit_print`ed is a `rgl` object, and changing it beforehand?  I'll admit I can't follow the logic of your code, but I was successful in avoiding the original `force.screenshot` problem with something like the following:

```r
render_fn <- function(x, options) {
    if (inherits(x, "<whatever>") {
        options$force.screenshot <- FALSE
        <something else that modifies x?>
    }
    knit_print(x, options=options)
    # could also knit_print multiple things with another `knit_print` call
}
knitr::opts_chunk$set(render=render_fn)
```

I hadn't ever used `fig.keep` before, and I still don't know how it works precisely, but I imagine you might be able to do quite a bit of the manipulation at this point, since you have access to the `fig.keep` option at this point (e.g., maybe you could get rid of them yourself?).  But since you're this far into the weeds on this issue, I think you probably know much better than I do.

**Comment by yihui** [comment]
Unfortunately the package **R.utils** happens to have an exported S3 generic function named `wrap()`, which will cause conflicts in packages that depend on **R.utils**, so I'll have to rename `wrap()` in **knitr** before exporting it. Not sure if you have suggestions on a new name (I guess most common verbs have been used in other packages, e.g., `bundle()` has been used in **packrat**).

**Comment by yihui** [comment]
I've tentatively renamed `wrap()` to `sew()`. Please let me know if you have other suggestions. Thanks!

**Comment by dmurdoch** [comment]
`sew()` seems unlikely to conflict with anything else.  Another possibility is to use a long name, since this isn't a function most users would want to use, e.g. `knit_wrap`.

**Comment by yihui** [comment]
Yes, `knit_wrap()` is a good candidate. I'll check the results of reverse dependency checks based on the name `sew()`. If any package breaks, I'll try `knit_wrap`. Thanks!
