### ISSUE TITLE
For sourcing external code, xfun::read_utf8('') does not work when using relative paths

### ISSUE THREAD

**Issue by krishnakumarg1984** [yihui/knitr#1868]
For sourcing external python files, if the source codes are located in a sub-folder titled `project_codes`, then

````
```{python, code=xfun::read_utf8('project_codes/script.py')}
```
````

does not work. After copying `script.py` to the root of the Rmarkdown document, this works fine though.  

Usually, code development takes prior to documentation, and it is important to support the inclusion of source codes  organized in a separate folder.

**Comment by yihui** [comment]
Could you please not delete [the issue guide](new) when filing issues? The issue guide asked for a reproducible example, which you didn't provide.

I tried to make an example, but I'm not able to reproduce the issue you reported: [test.zip](https://github.com/yihui/knitr/files/4843015/test.zip)

Please do follow the issue guide in the future. Thanks!

**Comment by retorquere** [comment]
The following seems to exhibit the described problem (which I also experience):

* when I knit, I get `hello` printed
* when I run the code chunks using `restart R and run all chunks` then the preview says `world`. When I remove the `print('world')` line, it just does nothing (but probably because it is running the empty body as an R script).

`main.R`:

````
---
title: "test"
author: "Me"
date: "6/17/2020"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(xfun)
```

```{r, code=xfun::read_utf8(here::here('test.R'))}
print('world')
```
````

`test.R`:

````
print('hello')
````

**Comment by krishnakumarg1984** [comment]
Hi,

Do we have some further thoughts on this?

**Comment by cderv** [comment]
@krishnakumarg1984 Can you provide a more reproducible example ? 

What is the structure of your project ? Where is `'project_codes/script.py'` relatively to your Rmd file ? 

See about "The working directory for R code chunks" in https://bookdown.org/yihui/rmarkdown-cookbook/working-directory.html

maybe it could help understand. 

We need more information to reproduce on our side what you are doing in order to help further.

@retorquere I don't think this is related. What you observe is I believe an issue with the IDE feature of running chunk that does not take into account the `code` chunk option as **knitr** / **rmarkdown** does when rendering.

**Comment by cderv** [comment]
@krishnakumarg1984 as explained in https://github.com/yihui/knitr/issues/1868#issuecomment-650823475 we cannot reproduce this It is working as expected. 

as there was no more activity on this to give a reproducible example, I'll consider this is working and close. 

Please reopen if it is still not working for you. Thank you!
