### ISSUE TITLE
toc_float: change bootstrap flex default 3:9 toc and content columns?

### ISSUE THREAD

**Issue by dan-reznik** [yihui/knitr#1875]
Is it possible to pass an argument (or drop a .css or js snippet) in the .Rmd of a html_document with a toc_float so that you don't get the default 3-9 (out of 12) flex/bootstrap column allocation? I would like to get for example 2 for toc and 10 for content.

Dan

**Comment by yihui** [comment]
Nex time could you please read and follow [the issue guide](new) exactly to provide all the required information? As requested, please do not ignore or delete the issue guide in your post, otherwise it is usually hard for us to help you. This seems to be a question instead of bug report, and the issue guide has instructions on where to ask questions.

Anyway, the 3-9 layout is hardcoded in the HTML template:
https://github.com/rstudio/rmarkdown/blob/fbd0b1f99f546a831cfb7b55a0b7bcc2351c6d53/inst/rmd/h/default.html#L451-L463
One way to change the layout is to copy this template, customize it (e.g., change 3 to 2 and 9 to 10), and apply it to your document: https://bookdown.org/yihui/rmarkdown-cookbook/html-template.html
