### ISSUE TITLE
encoding error with include_graphics

### ISSUE THREAD

**Issue by earthcli** [yihui/knitr#1883]
Usually I use the function knitr::include_graphics to include images to the word document. I met an error about the encoding when upgrade R to R4.0 using UTF-8. While it works fine with R3.6, would you please tell me how could I fix it?

Error in png::readPNG(path, native = TRUE, info = TRUE) : unable to open E:/椤甸潰_01.png

The Rmd file is as below:

geometry: margin=0cm
output: 
  word_document

{r 20200805161537,cache=FALSE,include=TRUE,echo=FALSE,message=FALSE,warning=FALSE,dpi=300,fig.width=4.7244,fig.height=2.7559,fig.align='default',fig.show='asis',out.width=NULL,comment=NA,background='#FFFFFF'}
plotsrc=c('E:/页面_01.png','E:/页面_02.png');knitr::include_graphics(plotsrc)

![test](https://user-images.githubusercontent.com/5924370/89394056-295b1280-d73e-11ea-9eb2-c58dc840e0b7.png)

**Comment by yihui** [comment]
Could you read and follow [the issue guide](new) exactly to provide all the required information? As requested, please do not ignore or delete the issue guide in your post, otherwise it is usually hard for us to help you. Thanks!

That said, I strongly recommend that you use relative paths instead of absolute paths (such as `E:/页面_01.png`). Absolute paths can be problematic in several possible ways.

To solve your original problem, use the argument `dpi = NA` in `include_graphics()`.

Again, please follow the issue guide next time.
