### ISSUE TITLE
Broken flexdashboard after a change in knitr

### ISSUE THREAD

**Issue by karoliskoncevicius** [yihui/knitr#1901]
By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

---

**NOTE**: this intermingles a couple of inter-related packages, I am submitting the issue to `knitr` first, as the issue producing the behaviour was tracked to the change in `knitr`.

Here is a simple Rmarkdown document example:

    ---
    output:
      flexdashboard::flex_dashboard:
        theme: united
    ---

    ```{r main_index}

    library(dygraphs)

    lungDeaths <- cbind(mdeaths, fdeaths)
    dygraph(lungDeaths)

    ```

It works on knitr v1.29 but fails on knitr v1.30 with the following error:

    > rmarkdown::render("index.Rmd")

    processing file: index.Rmd
      |........................................
      ordinary text without R code

      |.............................................................................................
    Error in validateCssUnit(sizeInfo$width) :
      CSS units must be a single-element numeric or character vector

Interestingly everything works if I manually revert this pull request in the newest knitr codebase: https://github.com/yihui/knitr/pull/1877

**Comment by atusy** [comment]
You can workaround the issue by explicitly specifying `fig.width|height` chunk options with single values.

flexdashboard specifies followings by default.

```
 $ fig.ext      : chr [1:2] "png" "mb.png"
 $ fig.width    : num [1:2] 6 3.75
 $ fig.height   : num [1:2] 4.8 4.8
```

HTML widgets fail to render if multiple sizes are given because `out.width.px` and `out.height.px` becomes multiple values.
They are given to `htmltools::validateCssUnit` which only accepts a single value vector.

This might be related to https://github.com/yihui/knitr/issues/1899

## Minimal reprex with html_document

````
---
output: html_document
---

```{r, fig.width=c(2, 3)}
library(dygraphs)

lungDeaths <- cbind(mdeaths, fdeaths)
dygraph(lungDeaths)
```
````

**Comment by karoliskoncevicius** [comment]
Thanks a lot for explanation @atusy .

So if I understood this part correctly - the defaults of `flexdashboard` are not compatible with the current change in `knitr`. In this case should the bug be sent upstream to `flexdashboard`?

**Comment by atusy** [comment]
@karoliskoncevicius 

Well, the defaults of `flexdashboard` are compatible images, but not with HTML widgets.
I'd rather say `htmlwidgets` is the one to be fixed so that they only use first value of figure size.

**Comment by yihui** [comment]
@atusy Sounds like a simple fix for the **htmlwidgets** package. Could you submit a PR there and ask @jcheng5 if he could consider a CRAN release? Thanks!

**Comment by atusy** [comment]
@yihui Sure! I will do it tonight

**Comment by atusy** [comment]
Will be fixed via https://github.com/ramnathv/htmlwidgets/pull/385

**Comment by cderv** [comment]
The fix in **htmlwidgets** should work but as it was strange to me that this broke recently. I dig a bit more. 

For a git bisect, I found the issue happens due to 33c9e9f990dd51d55299f8f4dab9369bb3fd8c81 by this PR https://github.com/yihui/knitr/pull/1877

This is because `fix_options` is creating the `out.*.px` options used by **htmlwidgets**. Previously, it was applying before the options hook of **flexdashboard** that sets two values (the second one if for mobile), and now it applies after so two values are calculated. Hence the issue with **htmlwidgets** that does not know how to deal with two values.

**Comment by cderv** [comment]
This is now fixed in htmlwidget. You can install the last version already on CRAN to make this work again. 
https://cran.r-project.org/package=htmlwidgets

**Comment by cderv** [comment]
Thanks @atusy !
