### ISSUE TITLE
Unexpected behavior with results='asis' with `output: github_document`

### ISSUE THREAD

**Issue by tomschenkjr** [yihui/knitr#1915]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

This is a continuation of this [StackOverflow](https://stackoverflow.com/questions/64599333/include-yaml-not-frontmatter-in-output-from-knitr) question. While generating a `README.md` from `README.Rmd`, there seems to be unexpected behavior while trying to generate a YAML block. This is when using `output: github_document`. As a simple example:

```r
```{r, results='asis', echo=FALSE}
cat("---\n
foo: bar\n
doh: ray\n
---")
```

Running the `cat()` in terminal the output is

```
---

foo: bar

doh: ray

---
```

However, when knitting the document the result is:

```
-----

foo: bar

doh: ray

-----
```

Five dashes are inserted instead of three.

Have attempted other permutations, such as:

```
```{r, results='asis', echo=FALSE}
cat("---",
"foo: bar",
"doh: ray",
sep="\n")
```

Which yields the following in the console

```
---
foo: bar
doh: ray
---
```

But after knitting, the results are entirely omitted from the Markdown document.

Environment:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763), RStudio 1.2.1335

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  evaluate_0.13   glue_1.3.0      graphics_3.5.1  grDevices_3.5.1
  highr_0.7       knitr_1.21      magrittr_1.5    markdown_0.8   
  methods_3.5.1   mime_0.6        stats_3.5.1     stringi_1.1.7  
  stringr_1.4.0   tools_3.5.1     utils_3.5.1     xfun_0.5       
  yaml_2.2.0   
```

**Comment by cderv** [comment]
I don't believe ***knitr** is for anything here. FWIW I think it is working fine. If you run, `knitr::knit` on the README.Rmd, you'll get a md file in which the result of `cat` is correctly kept. 

However here, you explicitly asked for Github Document format, that means to output a `.md` document using [Github Flavor Markdown](https://github.github.com/gfm/#thematic-break). and I believe GFM does not support YAML blocks - that is why it is disappearing.  

See this example with Pandoc

* YAML block are removed because not supported in gfm format

```sh
$ pandoc -t gfm
text before

---
foo: bar
doh: ray
---

text after
^Z
text before

text after
```

* `---` in Pandoc markdown is transformed in a sequence of dash for thematic break
```sh
$ pandoc -t gfm
---
^Z
------------------------------------------------------------------------
```

That is why you observed all this. This is perfectly expected as a result of [Pandoc ](https://pandoc.org/MANUAL.html)

What is exactly your expected output for the github document ? Github Flavour Markdown does not support yaml block in its content. Are you willing to have a yaml code block for code highlighting ? Or do you want to generate a mardkown document but not specifically using Github Flavored Markdown ? because there is `md_document()` for that where you can chose the markdown variant you want from what Pandoc supports.

I am closing this issue in favor of the stackoverflow question as there is no issue in knitr.
