### ISSUE TITLE
Unable to change default unnamed.chunk.label

### ISSUE THREAD

**Issue by rasyidstat** [yihui/knitr#1926]
Hi,

I would like to change the default `unnamed.chunk.label` from `unnamed-chunk` to `fig`. I already set `knitr::opts_knit$set(unnamed.chunk.label = "fig")` on the first of RMarkdown chunk but it did not work, the figure name still use `unammed-chunk`. Please advise and help to resolve this issue.

Thank you

**Comment by cderv** [comment]
Hi, 

It seems this option can't be changed from withing an Rmd file. I am not sure if this is for all `opts_knit` type of option or only some of them like this one.

Setting it before knitting works.
```r
knitr::opts_knit$set(unnamed.chunk.label = "fig")
knitr::knit("test.Rmd") 
# or rmarkdown::render("test.Rmd")
```

See `?knitr::opts_knit` for how to set this type of option globally in you Rprofile for an R session. 
This specific option is in the example of the help page also. 
I believe it would be : 
```r
options(knitr.package.unnamed.chunk.label = "fig")
```

**Comment by yihui** [comment]
> But before, @yihui is this expected behavior to set this option outside of the document only ?

@cderv Yes, because this label is used when the document is parsed, which happens before any code chunks are evaluated, so it would be too late if the option is specified inside a document.

For now, setting the option in `.Rprofile` (as you mentioned above) might be the best way to go. We could reconsider supporting this better in the future if the `.Rprofile` method is not satisfactory to @rasyidstat. Thanks!
