### ISSUE TITLE
 options(OutDec= ","): invalid version specification ‘3,6’ 

### ISSUE THREAD

**Issue by egoipse** [yihui/knitr#1943]
---

By filing an issue to this repo, I promise that

- [x ] I have fully read the issue guide at https://yihui.org/issue/.
- [ x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x ] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

***

I'm trying to render a vignette created by usethis::use_vignette() function. And, of course, since it's not written for US audience, I need to replace the decimmal separator: "," instead of ".".

I tried the usual way: `options(OutDec= ",")` in the first chunk.

However, I got the following error on RMarkdown tab:

```
Error: invalid version specification ‘3,6’
```
Clearly, here the `options` function changes the way some `knitr` function or piece of code is checking the current R version, since R, by default, would not ask for `3,6`, but for `3.6`.

The error disappears as soon as the `options(OutDec= ",")` is removed from the chunk.

It seems this is a very [popular issue](https://github.com/daqana/tikzDevice/issues/57), and [not only for this package](https://github.com/r-spatial/mapview/issues/353).

Here's my  session info:

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS, RStudio 1.3.1093

Locale:
  LC_CTYPE=es_CL.UTF-8       LC_NUMERIC=C              
  LC_TIME=es_CL.UTF-8        LC_COLLATE=es_CL.UTF-8    
  LC_MONETARY=es_CL.UTF-8    LC_MESSAGES=es_CL.UTF-8   
  LC_PAPER=es_CL.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=es_CL.UTF-8 LC_IDENTIFICATION=C       

Package version:
  evaluate_0.14   glue_1.4.2      graphics_4.0.3 
  grDevices_4.0.3 highr_0.8       knitr_1.30     
  magrittr_2.0.1  markdown_1.1    methods_4.0.3  
  mime_0.9        stats_4.0.3     stringi_1.5.3  
  stringr_1.4.0   tools_4.0.3     utils_4.0.3    
  xfun_0.20       yaml_2.2.1   
```

**Comment by cderv** [comment]
Thanks for the report.

I don't think this is an issue on **knitr** itself as when I tries with an example vignette I don't get this error. But I'll check

I think it could come from one of your packages used in your vignette that could have the bug described in https://github.com/r-spatial/mapview/issues/353 you linked to. 

This is because `outDec` will change the way decimal is used for all R behavior, including some basic things like `as.character`
``` r
as.character(3.5)
#> [1] "3.5"
withr::with_options(list(OutDec = ","), as.character(3.5))
#> [1] "3,5"
```

and when comparing version, there will some automatic conversion from numeric to character to numeric version object.

This is a reprex of the error

``` r
numeric_version(3.5)
#> [1] '3.5'
withr::with_options(list(OutDec = ","), numeric_version(3.5))
#> Error: invalid version specification '3,5'
```

No we know the why, can you look into the list of package you are using in your vignette ? 

Also can you run 
```r
rmarkdown::render("your.Rmd") # will error
traceback() # or rlang::last_trace()
````

This will help identify where the error is thrown.
