### ISSUE TITLE
valign with kables() does not work with pagedown html_paged template.

### ISSUE THREAD

**Issue by andrew-fuller** [yihui/knitr#1964]
Hi all, 

I have been working on a report that utilizes side by side tables with kable. I was running into an issue where for some reason in the markdown editor the tables appear to print side by side vertically aligned but when I knit with pagedown they are no longer aligned.

Some example code below taken from the knitr documentation. 

Any help with how to get around this would be greatly appreciated!

````
---
title: "A Multi-page HTML Document"
author: "Yihui Xie and Romain Lesur"
date: "`r Sys.Date()`"
output:
  pagedown::html_paged:
    toc: true
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r cars}

d1 <- head(cars, 3)
d2 <- head(mtcars[, 1:3], 5)
# data objects d1 and d2 are from the previous code chunk
knitr::kables(
  list(
    # the first kable() to change column names
    kbl(
      d1, col.names = c('SPEED', 'DISTANCE'), valign = 't', format = "html"
    ),
    # the second kable() to set the digits option
    kbl(d2, digits = 0, valign = 't', format = "html")
  ),
  caption = 'Two tables created by knitr::kables().'
) %>%
  kable_styling()
```
````

**Comment by cderv** [comment]
Thanks for the report @andrew-fuller ! I edited your post to make it more readable. 
For next time, see about the trick here https://yihui.org/issue/#please-format-your-issue-correctly

First, your are setting `valign` : This is useful when you are doing latex output and not HTML output. So it will have not effect on the output from **pagedown**. I guess you may have expected this to work out of the box right ? 

With HTML, you need to customize by CSS. If you saw https://bookdown.org/yihui/rmarkdown-cookbook/kable.html, you have the correct alignment you described because **bookdown** will set the correct CSS. `html_document` will also do, but **pagedown** won't set it by default. 

You'll need to customize it by adding this chunk in your document 
````markdown
```{css}
.kable_wrapper > tbody > tr > td {
    vertical-align: top;
}
```
````

I let you try and confirm; Thanks!

**Comment by andrew-fuller** [comment]
Thanks for all your help @cderv ! I will make sure to have my posts edited properly in future. 

In hindsight it seems I was stating the obvious then, that valign does not work with html. 

I tried out the CSS you gave and everything is working perfectly now. 

Much appreciated!

**Comment by cderv** [comment]
Glad it works! 

@yihui do you think we should have this kind of css for `kables()` in pagedown by default? Or is it something to set a the user level? 

I believe you would want it align this way most often and is why I consider the former.

**Comment by yihui** [comment]
> do you think we should have this kind of css for `kables()` in pagedown by default?

Sounds good to me.
