### ISSUE TITLE
dev = "cairo_pdf" and fig.cap interaction

### ISSUE THREAD

**Issue by TTT12-dumb-dumb** [yihui/knitr#1974]
Hi, it seems that specifying `dev = "cairo_pdf"` doesn't allow whatever I feed into `fig.cap` to be outputted.  I'm wondering if this is expected or if I'm missing a workaround (I couldn't find anything through searching).  I'm using cairo_pdf to be able to output a plot using `theme_ipsum()` to pdf, in case there's a workaround there.  

In the meantime, it's just a few plots so I can go in and manually edit the .tex file, but wondering if I'm just missing an obvious solution?

Thanks!

**Comment by cderv** [comment]
Can you share a reproducible example as asked in the [issue guide](https://yihui.org/issue/) ? 

It works for me 
````markdown
---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, fig.cap = "A plot", dev = "cairo_pdf"}
plot(mtcars)
```
````
![image](https://user-images.githubusercontent.com/6791940/110935548-db3f6a80-832f-11eb-88e5-de0cb423269d.png)

I may have missed something but you need to provide more information. Thank you.

**Comment by TTT12-dumb-dumb** [comment]
Apologies; I realize that all the chunks I was specifying `dev = "cairo_pdf"`, I was _also_ not leaving an extra line after the closing 3 backticks in for the chunk, which prevented the caption from appearing.

<pre><code>``{r dev = "cairo_pdf", fig.cap="test."}
data(iris)
library(ggplot2)
library(hrbrthemes)
ggplot(iris, aes(x = Petal.Width, fill = Species)) + 
  geom_density() +
  theme_ipsum() 
```</code></pre>

The only difference between the two knits was the extra line in the document.  Embarrassing oversight by ding-dong me... Thank you for your time.

![image](https://user-images.githubusercontent.com/53317737/111021380-ca2b4380-8399-11eb-9eab-811a90db414b.png)

![image](https://user-images.githubusercontent.com/53317737/111021381-d3b4ab80-8399-11eb-8284-cd861e9d14f5.png)

**Comment by cderv** [comment]
Oh indeed. When there is no new line after the chunk, **knitr** will produce this markdown syntax

```markdown
![A plot](test_files/figure-latex/unnamed-chunk-1-1.pdf) 
words words
```` 

With only one space on the first line after the plot, meaning no new paragraph. Pandoc will consider this as an inline image.
```sh
>pandoc -t latex
![A plot](test_files/figure-latex/unnamed-chunk-1-1.pdf) 
words words
^Z
\includegraphics{test_files/figure-latex/unnamed-chunk-1-1.pdf} words
words
```
Pandoc requires a new paragraph to interpret the [images as a figure](https://pandoc.org/MANUAL.html#extension-implicit_figures)
```sh
>pandoc -t latex
![A plot](test_files/figure-latex/unnamed-chunk-1-1.pdf)

words words
^Z
\begin{figure}
\centering
\includegraphics{test_files/figure-latex/unnamed-chunk-1-1.pdf}
\caption{A plot}
\end{figure}

words words
```

I am not sure there is much we can do to improve. 

@yihui is this expected behavior ? Do you think this needs improvement ? Like not relying on Pandoc conversion and directly generate the TeX markup ?

I am wondering this because it happens in some cases already if some options are specified.e.g 
same example but adding `out.width` chunk option bypasses Pandoc
 ````markdown
---
title: "Untitled"
output: 
  pdf_document:
    keep_tex: true
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, fig.cap = "A plot", dev = "cairo_pdf", out.width=200}
plot(mtcars)
```
words words
````

This create block figure with caption, and not inline as before.
````markdown
```r
plot(mtcars)
```

\begin{figure}
\includegraphics[width=200px]{test_files/figure-latex/unnamed-chunk-1-1} \caption{A plot}\label{fig:unnamed-chunk-1}
\end{figure}
words words
````

So the output is not the same depending if option is set or not. 

This could be something to think more about on a general topic to make hook_plot coherent between format with expected and foreseen output.

What do you think ?
