### ISSUE TITLE
Output.var in code chunk is agnostic of quotes until knitting

### ISSUE THREAD

**Issue by julieinsan** [yihui/knitr#1976]
When editing an Rmarkdown doc, I can run each of these chunks individually and get a variable called "thing" after execution in my global env.
````r
```{sql connection=con, output.var=thing}
select * from table
```
````

````r
```{sql connection=con, output.var="thing"}
select * from table
```
````

**but**, if the name is **unquoted** and I try to knit I get this error and knit fails:
*Error in eval(x, envir = envir) : object 'thing' not found*

This, I would think, is unwanted.  While I appreciate the flexibility in some circumstances, I think the rule should be consistent no matter how the chunk is run (manual or knit).

Here's my session info:

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363), RStudio 1.4.1106

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  assertthat_0.2.1  base64enc_0.1.3   BH_1.75.0.0       bit_4.0.4         bit64_4.0.5       blob_1.2.1        cli_2.1.0         commonmark_1.7    compiler_4.0.3   
  cpp11_0.2.4       crayon_1.3.4      crosstalk_1.1.0.1 DBI_1.1.0         digest_0.6.27     dplyr_1.0.2       ellipsis_0.3.1    evaluate_0.14     fansi_0.4.1      
  fastmap_1.1.0     generics_0.1.0    glue_1.4.2        graphics_4.0.3    grDevices_4.0.3   highr_0.8         hms_0.5.3         htmltools_0.5.1.1 httpuv_1.5.4     
  jsonlite_1.7.2    knitr_1.30        later_1.1.0.1     lazyeval_0.2.2    lifecycle_0.2.0   magrittr_2.0.1    markdown_1.1      methods_4.0.3     mime_0.9         
  odbc_1.3.0        pillar_1.4.6      pkgconfig_2.0.3   promises_1.2.0.1  purrr_0.3.4       R6_2.5.0          Rcpp_1.0.6        rlang_0.4.10      rmarkdown_2.5    
  rstudioapi_0.13   shiny_1.5.0       sourcetools_0.1.7 stats_4.0.3       stringi_1.5.3     stringr_1.4.0     tibble_3.0.4      tidyr_1.1.2       tidyselect_1.1.0 
  tinytex_0.27      tools_4.0.3       utf8_1.1.4        utils_4.0.3       vctrs_0.3.4       withr_2.3.0       xfun_0.19         xtable_1.8-4      yaml_2.2.1  

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Thanks for the report. 

> This, I would think, is unwanted. While I appreciate the flexibility in some circumstances, I think the rule should be consistent no matter how the chunk is run (manual or knit).

By manual you mean clicking the green arrow "Run Current Chunk" in the IDE ? 

I asked because I know about https://github.com/rstudio/rstudio/issues/6675 with the IDE where chunk option are not evaluated correctly when running interactively, compared to when knitting.

Usually with **knitr** chunk option could take a variable, in which case the value of this variable is used, or a value directly, in which case this value is used. 

So this error with **knitr** seems expected: `Error in eval(x, envir = envir) : object 'thing' not found`
and maybe it is the IDE which should not used unquoted variable as name. 🤔 it seems to show the IDE does not evaluated the chunk option as **knitr** does.

I believe every engine function the same regarding **knitr** option, with chunk options being evaluated by **knitr** before being used by the engine. 

@yihui what is your thought on that ? Is this something we should look into with the IDE team ? The different behavior for notebook use interactively in the IDE compared to knitting / rendering in console or with button is something we need already to discuss with them. Maybe this is to add ? 

cc @apreshill

**Comment by julieinsan** [comment]
I wholeheartedly agree with this:
> I believe every engine function the same regarding knitr option, with chunk options being evaluated by knitr before being used by the engine.

and
> So this error with knitr seems expected: `Error in eval(x, envir = envir) : object 'thing' not found`

At the same time, there is some convenience gained by not needing to quote a name...

**Comment by yihui** [comment]
> what is your thought on that ? Is this something we should look into with the IDE team ? The different behavior for notebook use interactively in the IDE compared to knitting / rendering in console or with button is something we need already to discuss with them. Maybe this is to add ?

Yes, please move this issue to the IDE. I hope the IDE could not make the exception in this case, i.e., it should require `output.var` to be properly quoted. For **knitr**, the chunk options are supposed to be valid R code, and they are evaluated without any clever tricks (well, except for the chunk label, which may not be quoted). Making the quotes optional will introduce ambiguity---**knitr** won't know if `thing` itself is the output variable name, or the value of the `thing` variable is the output variable name.

Thanks!
