### ISSUE TITLE
Option to wrap entire chunk in classed div

### ISSUE THREAD

**Issue by hadley** [yihui/knitr#2000]
To support certain types of formatting it would be very useful to wrap the entire chunk in a classed div. Currently I'm doing that with a chunk knit_hook:

```R
indent <- function(x, indent) {
  if (is.null(indent)) {
    return(x)
  }
  paste0(indent, gsub("\n", paste0("\n", indent), x))
}

knitr::knit_hooks$set(chunk = function(x, options, ...) {
  if (!options$echo){
    return(x)
  }
  x <- gsub("\033", "\u2029", x, fixed = TRUE)
  x <- paste0("<div class='sourceCode'>", x, "</div>")
  indent(x, options$indent)
})
```

But it would be very useful if this was a top-level chunk option, e.g.

```R
knitr::opts_chunk$set(class.chunk = "sourceCode")
```

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by atusy** [comment]
I like the idea. I would also want

- `attr.chunk` like `attr.source` and others
- `div.chunk` which controls if div is HTML's `<div>` or fenced div, `:::`.
    - I prefer the latter but HTML might be better as `knit` does not specify the markdown flavor.
    - `wrap.chunk = c("<div %s>", "<div>")` is the another idea (`%s` is the place holder to be substituted by attributes). In this way, we can wrap with other elements like `<section>`, `<details>` and so on. Maybe we can add both and `wrap.chunk=NULL` by default and prefer `wrap.chunk` to `div.chunk` if `wrap.chunk` is specified.

**Comment by atusy** [comment]
Some thoughs on this:

## Implementation is easy

Just insert a function before triggering the chunk knit_hook  in two places.

https://github.com/yihui/knitr/blob/36e6a30b4c8eb29d9d9d0e87a669b83c697234a7/R/block.R#L307-L308

https://github.com/yihui/knitr/blob/36e6a30b4c8eb29d9d9d0e87a669b83c697234a7/R/block.R#L144-L145

## Design is difficult.

Users may be confused for some reasons.
Of course we can document the behavior, but I love simple things which requires less docs...

- @hadley 's example wraps the chunk *conditionally*, but users may expect unconditional wrapping.
- Wrap and chunk knit_hook should happen in this order, however, it is not clear for users without the documentation.
  Also, the document may become complex because we need to refer to multiple sections to understand the behavior.
  The chunk knit_hook is documented at ["Output hooks"](https://yihui.org/knitr/hooks/#output-hooks).
  OTH, the suggested `class.chunk` should belong to ["Chunk Options"](https://yihui.org/knitr/options/#chunk-options).
- Although I suggested `wrap.chunk` and other options, they are essentially some (but still slightly complex) shortcuts on chunk `knit_hook`. I now feel it does not worth adding.

## Alternative

I would recommend to keep on using the chunk `knit_hook`.
If your pain is conditional `class`, then you can refer to `class.chunk` chunk option in the body of the hook.

```diff
  knitr::knit_hooks$set(chunk = function(x, options, ...) {
    if (!options$echo){
      return(x)
    }
    x <- gsub("\033", "\u2029", x, fixed = TRUE)
-   x <- paste0("<div class='sourceCode'>", x, "</div>")
+   if(!is.null(options$class.chunk)) x <- sprintf("<div class='%s'>%s</div>", options$class.chunk, x)
    indent(x, options$indent)
  })
```

**Comment by hadley** [comment]
My use case doesn't require any complicated conditional formatting; I just want some easy way to wrap all chunks in a div with known class (I don't even care what that class is, or to even have the ability to change it). Being able to identify a complete chunk (i.e. all input and output however it is interleaved) allows for custom css formatting in ways that knitr does not currently support.

**Comment by atusy** [comment]
@hadley 
Okay... I minimally implemented. Is this something you want?
https://github.com/yihui/knitr/pull/2099

**Comment by hadley** [comment]
Yeah, that's exactly what I'm looking for 😄
