### ISSUE TITLE
Custom knit_print not called in interactive mode - nothing is visible

### ISSUE THREAD

**Issue by LukasWallrich** [yihui/knitr#2009]
I am building a package that creates HTML code, which should be printed asis in RMarkdown documents. Based on the vignette, I have managed to write and register a knit_print method (below), which works perfectly when knitting documents. However, it is not called when I just run a chunk in interactive mode - in that case, the custom print method is called, but nothing appears, even when the print method uses exactly the same code. 

Calling print() or knit_print() explicitly works in interactive mode - but I need to get implicit printing to work. A minimal reprex package can be found here:  https://github.com/LukasWallrich/knitrPrintTest

I have looked at the code of other packages - e.g., htmltools - and it appears that knit_print rather than print gets called there in interactive mode ... but I have no idea why. Any suggestions would be much appreciated. 

```
#' @exportS3Method knitr::knit_print timesaveR_raw_html

knit_print.timesaveR_raw_html <- function(x, ...) {

#Some processing ommitted
  
  structure(x, class = "knit_asis")
}
```

I asked about this on SO two months ago: https://stackoverflow.com/questions/66653963/printing-custom-html-objects-asis-in-rmd-chunks-why-does-x-fail-but-printx-w

---

By filing an issue to this repo, I promise that

- [x ] I have fully read the issue guide at https://yihui.org/issue/.
- [ x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
The RStudio IDE is handling the printing of the chunk when interactive. It is indeed calling `print` and not `knit_print` it seems. The latter is only use within knitr processing during render. The IDE is notebook is evaluating code as in the R console (you can choose to output in the document or in console, but in both case the code is sent to the R console). So currently, it does not use the `knit_print` method but this is a feature request https://github.com/rstudio/rstudio/issues/1626 you can add a 👍 there.

> I am building a package that creates HTML code, which should be printed asis in RMarkdown documents.

This does not mean you can't do what you want I think.  

For this, I would follow the example of HTML widgets and other packages that do HTML (bslib, shiny, htmltools, ...). Why not use **htmltools** package directly ? This is what I would do: 
To output HTML in R, I would use the **htmltools** package. You'll find all the tool you need to build HTML with the benefit of getting the nice printing you are looking to get. Basically, your small example is kind of trying to do exactly what htmltools is doing. 

````markdown
---
title: test
output: html_document
--- 

```{r}
hello <- function() htmltools::h1("Hello")
```


```{r}
hello()
```

```{r}
hello2 <- function() htmltools::HTML("<h1>Hello2</h1>")
```

```{r}
hello2()
```

````

No need to have you're own knit print method in this case as **htmltools** have all that you need. it will included the classes, attributes, methods so that it prints correctly in knitr and in the IDE interactively. 

Why no benefit from this ? Have you any constraint preventing to use this ?

**Comment by cderv** [comment]
Also regarding your SO question, I don't really know why using knitr::asis_output in a print function makes the value not showing... 🤔 

````r
x <- "<b>Hi there!</b> How are you?"
class(x) <- "myhtml"
x # show something

print.myhtml <- function(x) {
  knitr::asis_output(x)
}

x # show nothing
````

I must missed something in how this works... 🤔

**Comment by LukasWallrich** [comment]
Thanks a lot! This works. There were two constraints - I needed to (conditionally) print a specific part of the object and did not want the messages regarding S3 methods overwritten by htmltools ... but a function like the below does exactly what I need.

```
print.timesaveR_raw_html <- function(x, ...) {
  if (TRUE) {
    res <- x$html_code
  } 
  suppressMessages(print(htmltools::HTML(res)))
}
```

**Comment by LukasWallrich** [comment]
Unfortunately, not quite there yet - your hello2() (and thus my approach) works well from an RMarkdown chunk, but not in the console. If it is run there, the code is printed, instead of the Viewer being used. 

That seems to be an htmltools issue, but I was wondering whether that is only the case on my machine and whether you can suggest a workaround (e.g, call html_print manually *if* the code is run in the console - but I am not sure what that condition would be)?

**Comment by LukasWallrich** [comment]
I found a possible condition [here](https://community.rstudio.com/t/customizing-general-objects-formatting-output/11262) - with that the print function works in both code chunk and console, but I have no idea what that code does and thus whether it is robust. Any thoughts/alternatives? Otherwise, we can close this.

`if (interactive() && length(as.environment("tools:rstudio")$.rs.S3Overrides) > 0L)`

**Comment by cderv** [comment]
>  your hello2() (and thus my approach) works well from an RMarkdown chunk, but not in the console. If it is run there, the code is printed, instead of the Viewer being used.

This is a **htmltools** feature. Component can be set as browsable to be open in Viewer. But this should not be the default

```r
# default element
hello2 <- function() htmltools::HTML("<h1>Hello2</h1>")
# is it browsable ? NO 
htmltools::is.browsable(hello2()) # FALSE

# Make it browsable
hello3 <- function() {
  htmltools::browsable(
    htmltools::HTML("<h1>Hello2</h1>"),
    value = TRUE
  )
}
# Now it is 
htmltools::is.browsable(hello3()) # TRUE

# Will cat in console
hello2()
# Will open in Viewer
hello3()

```

This is all **htmltools** features and behavior here.

**Comment by LukasWallrich** [comment]
Thanks - that is great!
