### ISSUE TITLE
include_url results in enc2utf8(x): argument is not a character vector

### ISSUE THREAD

**Issue by systemnova** [yihui/knitr#2012]
When calling knitr::include_url("https://www.yihui.org") in a Rmd notebook i get the following error:

```
Error in enc2utf8(x) : argument is not a character vector 

Traceback:
3. writeLines(enc2utf8(x), con = mdfile, useBytes = TRUE) 
2. print.knit_asis(x) 
1. (function (x, ...) 
     UseMethod("print"))(x) 
```

I'm running:

| Environment|Version |
| ---:|:---|
knitr | 1.33
platform  | x86_64-apple-darwin17.0                          
version.string  | R version 4.0.5 (2021-03-31)

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
This is an issue with the RStudio IDE https://github.com/rstudio/rstudio/issues/6476 and it must be fixed there. 

@yihui can we try to make this kind of fix go faster with the IDE team or would the best change be to do a PR ourself for the code in the IDE that cause this error ? (not saying it would be easy or I know what to do yet 😅 )

**Comment by cderv** [comment]
Duplicate of #1820

**Comment by yihui** [comment]
@cderv I can see two possible ways to proceed:

1. We help fix it in the IDE. A relatively simple fix is to test if `x` can be coerced to character by `as.character()` before trying to write it to a file. This fix should be familiar to you since you just did one not long ago.
2. We fix it in knitr. The reason that the result of `include_url()` has the class `knit_asis` is because I want `knit_print()` to preserve `x` as is: https://github.com/yihui/knitr/blob/440d1a694e791f5516500472fe99cad84237eaeb/R/output.R#L700 which will be handled by `sew()` later: https://github.com/yihui/knitr/blob/440d1a694e791f5516500472fe99cad84237eaeb/R/output.R#L629 or by `html_screenshot()` if the output format is not HTML: https://github.com/yihui/knitr/blob/440d1a694e791f5516500472fe99cad84237eaeb/R/plot.R#L566 Now it seems the IDE does not recognize the class `knit_embed_url` when the object has the class `knit_asis` at the same time, we can avoid using the `knit_asis` class. For example, we could use the class name `knit_asis_url` instead, and define the S3 method `knit_print.knit_asis_url`.

Technically, the first option might be the easiest. However, the release of IDE comes at lower speed than the release of **knitr**, so if we aim to fix this as quickly as possible, the second option should be easier (unless we are close to the next release of the IDE).

**Comment by systemnova** [comment]
Definately not the right place to ask. But i was wondering if there is option to knit only a single chunk without evaluating all the other code?
ie. Export just the output from this chunk to html/pdf/png

**Comment by cderv** [comment]
By doing the above change, it works. RStudio IDE will use a regular print for this content

We'll get this: 
![image](https://user-images.githubusercontent.com/6791940/121547327-56d2b580-ca0c-11eb-8a4b-3ac12249e2d3.png)


I think it is best that an error but I wonder if we should offer a `print.knit_asis_url` that format output differently ?

**Comment by cderv** [comment]
> Definitely not the right place to ask

@systemnova yes this is not the right place. Please follow the issue guide next time and ask question in Q&A site

>  i was wondering if there is option to knit only a single chunk without evaluating all the other code?
ie. Export just the output from this chunk to html/pdf/png

You could deactivate `eval` and `echo` for all chunk except one so your document would contain only the content for the one activated chunk. 
You could also use some tricks to  tweak behavior. See the R Markdown Cookbook (https://bookdown.org/yihui/rmarkdown-cookbook/) for recipes that you may found useful (`purl()`, `knit_exit()`, hooks, ...)

Please ask on Q&A site with an example to get some help from the community. We also watch out for unanswered question so if we have insight we'll also share there. Thanks !
