### ISSUE TITLE
Change default `strip.white` value when `collapse = TRUE`

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#2046]
Following #2011, a breaking change was reported in https://github.com/rstudio/rmarkdown/issues/2220

Basically, when `collapse = TRUE`, blank lines are stripped by default because `strip.white = TRUE` is the default, and it applies now on those chunk. 

We probably want to make `strip.white = FALSE` the default when `collapse = TRUE` if possible.

**Comment by cderv** [comment]
I tried to tackle this but did not find exactly where to apply a modification.
Do we have a way to detect if an option is currently default value or set on a chunk by the user ? Because unless we revert, I think here we want to change the default strip.white value when collapse = TRUE on a chunk or a globally, unless specify by the user in which case we want to keep stip.white = FALSE.

Is this done by a knitr hook ? Is there another mechanism ?

**Comment by yihui** [comment]
One idea is to set `strip.white = NA` by default: https://github.com/yihui/knitr/blob/ef4a475cb4b42cecb6e50cc6d6eb8da26561262d/R/defaults.R#L73

and then set it to `TRUE` or `FALSE` inside `fix_options()` depending on the value of `collapse`: https://github.com/yihui/knitr/blob/ef4a475cb4b42cecb6e50cc6d6eb8da26561262d/R/utils.R#L248

Then we know that if it is `NA`, users didn't set it and we can "fix" it. Otherwise we don't touch it.

**Comment by yihui** [comment]
The comment is no longer totally true :)
