### ISSUE TITLE
How to persist a variable across chunks with custom language engine?

### ISSUE THREAD

**Issue by abalter** [yihui/knitr#2065]
The fact that `knitr` includes the ability to easily [register custom engines](https://bookdown.org/yihui/rmarkdown-cookbook/custom-engine.html) is amazing!

The [SQL `knitr` example](https://github.com/yihui/knitr-examples/blob/master/115-engine-sql.Rmd) the SQL engine is a great example of how to place data from the chunk into the external environment. I plan to try that with bash.

However, is there an example for how to write a language engine that can persist variables between chunks? For instance, what is a minimalistic example of how `reticulate` reconnects to a running python kernel rather than just passing text to one through `system2`?

**Comment by yihui** [comment]
This is definitely not easy. I don't know much about the implementation details of **reticulate**, but I doubt if it can be made minimal since it involves some C-level stuff.

Another possible way to is socket connection. I had an experiment from 2013: https://github.com/yihui/runr If you are really interested in it, I'll be glad to transfer this package to you and let you develop/maintain it.
