### ISSUE TITLE
`knitr::kable` caption appears below table in markdown output

### ISSUE THREAD

**Issue by turbanisch** [yihui/knitr#2074]
Knowing that @yihui has a strong preference for captions appearing *above* tables, I was wondering why they appear *below* the table in markdown output:

``````
---
title: "Test"
output: github_document
---

```{r}
knitr::kable(mtcars, caption = "mtcars")
```
``````

Specifying `format = "pipe"` or `format = "simple"` does not seem to help.

My original question on stackoverflow is here: https://stackoverflow.com/questions/69868494/how-to-add-a-caption-above-a-table-with-knitrkable 

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
The format of the table written depends on the output format, and the output table depend on the Pandoc conversion. 

So here, `knitr::kable()` will use `format = "pipe"`  by default, which use [Pandoc's `pipe_tables`](https://pandoc.org/MANUAL.html#extension-pipe_tables). `format = "simple"` uses [Pandoc's `simple_table`](https://pandoc.org/MANUAL.html#extension-simple_tables). 
Both can take caption written in the md file to convert above or below: See https://pandoc.org/MANUAL.html#extension-table_captions

**knitr** will write this caption in the knitted md file above the table 
https://github.com/yihui/knitr/blob/b09cbc151a5531daec2a72eadaefdd565b633646/R/table.R#L443-L446

But here you are asking to convert to github document. This will use the `gfm` format. I don't think Github Flavored Markdown supports caption in table. So Pandoc will take the caption and write it as text below the table. 

Takes this `.md` file written in Pandoc's markdown
````
Table: Demonstration of pipe table syntax.

| Right | Left | Default | Center |
|------:|:-----|---------|:------:|
|   12  |  12  |    12   |    12  |
|  123  |  123 |   123   |   123  |
|    1  |    1 |     1   |     1  |
````

It will be converted to Github Flavored mardkown by pandoc this way
````
❯ pandoc -t gfm test.md
| Right | Left | Default | Center |
|------:|:-----|---------|:------:|
|    12 | 12   | 12      |   12   |
|   123 | 123  | 123     |  123   |
|     1 | 1    | 1       |   1    |

Demonstration of pipe table syntax.
````

That is just how this is supposed to work because GFM does support caption I believe.

**Comment by turbanisch** [comment]
Thanks for the explanation! I wasn't aware of the fact that it is pandoc that changes the position of the caption. Even if it appears only as plain text in GFM, I would still prefer it to be positioned above the table but of course it does not make sense to tweak knitr's behavior just for this case.
