### ISSUE TITLE
Feature request: function to convert chunk options to YAML-style

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [yihui/knitr#2082]
It would be neat to have a function that takes an R Markdown document and converts the chunk options to YAML-style. I'm thinking functionality like the one provided in [Rd2roxygen](https://cran.r-project.org/web/packages/Rd2roxygen/index.html), but for processing the chunk options.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
I like this idea ! Thanks for the suggestion. 

It would be easy to convert to multiline chunk options as there is no change in the way it will be processed
````markdown
```{r}
#| echo = FALSE, fig.width = 10,
#| fig.cap = "This is a long caption."

plot(cars)
```
````
This is because it will be parsed as R code for option. You can use variables for example

However, for YAML style, it will be processed as YAML so you can't use R code directly. 
It can't be used for evaluating option. 

<details>
<summary>Example</summary>

````markdown
---
title: "Test"
output: html_document
---

```{r}
show_msg <- TRUE
```

```{r}
#| message = show_msg
knitr::opts_current$get("message")
```

```{r}
#| message: show_msg
knitr::opts_current$get("message")
```
````

would render to 

````markdown
---
title: "Test"
output: html_document
---

```r
show_msg <- TRUE
```

```r
knitr::opts_current$get("message")
```

```
## [1] TRUE
```

```r
knitr::opts_current$get("message")
```

```
## [1] "show_msg"
```
````

</details>

So this would be trickier to be able to convert to the latter. We would need to detect that a variable is used and not use the YAML form. 

I think you have the latter block in mind ? 

We could also offer such function with this limitation, warn that there could be issues and let the user fix the different YAML block. 

Just sharing thought on this so we all agree before one does anything

**Comment by mine-cetinkaya-rundel** [comment]
I was thinking about converting

```
{r echo = FALSE, fig.width = 10, fig.cap = "This is a long caption."}
```

to

```{r}
#| echo = FALSE, fig.width = 10,
#| fig.cap = "This is a long caption."
```

**Comment by cderv** [comment]
That seems something not so complicated to do. We already provide a helper in **bookdown** (`bookdown::fence_theorems()`) to convert between theorem syntax. We could add one here. 

@yihui does that sound ok to you ?

**Comment by yihui** [comment]
Yes, that sounds helpful. As you mentioned, converting the chunk options to the YAML style can be tricky, but simply moving them to `#|` and keeping the original comma-separated syntax (and optionally wrapping the lines) should not be hard to implement.

Note that one option per line like

```r
#| echo = FALSE,
#| fig.width = 10,
#| fig.cap = "This is a long caption."
```

can be a little tricky, though. This could be a fun `getParseData()` exercise, and I can tell you more if you are interested in implementing it.

**Comment by cderv** [comment]
I'll reopen that one as a reminder to deal with YAML format now.

**Comment by cderv** [comment]
@mine-cetinkaya-rundel dev version of **knitr** will now contain a function to convert `.qmd` document chunk option to YAML format. 

````r
knitr::convert_chunk("doc.qmd", output = identity)
````

For file with `.qmd` extension, the `type = "yaml"` will be the default. Otherwise, it needs to be added on the function call. 
Using `output = identity` will overwrite the input file, you can use another filename to save in another file. 

Unevaluated R expression (list, variables, ...) will be prefix with the `!expr` tag in the YAML. 

Hope it will work great on your projects and documents
