### ISSUE TITLE
questions on knit2pdf (output only allows ".tex" file extension,  can't produce to different folder, no clean arg)

### ISSUE THREAD

**Issue by shrektan** [yihui/knitr#2113]
Hi, 

I've been using `knitr::knit2pdf()` for years but there're some questions on designing that I don't quite understand since the very beginning:

1. The `output` argument must be with ".tex" file extension. It just produces a pdf file with the same name. Since the name is `knit2pdf()`, shouldn't it allow a ".pdf" file extension?
2. There's no way of removing the "tex" and "log" files, automatically.
3. The value provided to the `output` argument must be in the same folder of the Rnw file. Why can't it allow generating the output into another folder?

Is it because of historical reasons or am I using the wrong function?

**Comment by yihui** [comment]
1. The `output` argument is passed to `knit()`, which is why the file extension needs to be `.tex` instead of `.pdf`, but you are right that this is counterintuitive, and `.pdf` should be allowed.
2. This function should have a `clean` argument.
3. Path issues are usually quite complicated. The main problem is when the `.tex` file uses external files such as plots. Then we need to make sure the working directory for LaTeX is correct when compiling the document. For example, for `knit2pdf('input.Rnw', output = 'another/dir/output.tex')`, we have to make sure 1) the plots are generated to the correct dir, 2) the `\includegraphics{}` commands use the correct relative paths, and 3) LaTeX compiles the .tex file in the correct working directory, or specify the correct `-output-directory` argument to LaTeX (https://github.com/yihui/tinytex/commit/66a4e52d4d4f33bb247dee782de36a510d16cca5).

1 and 2 are relatively easy to solve. For 3, the easiest solution might be generating the `.pdf` in the same directory as `.Rnw` first, and then move it to the desired directory. However, if the user doesn't have write permission of the directory of the `.Rnw` document, this solution won't work...

**Comment by shrektan** [comment]
I think moving the pdf files to the desired destination is good enough and the most reliable way. If the user doesn't have the write permission, it shouldn't work any way.
