### ISSUE TITLE
unicode escape character (generated by **dplyr** warning?) generates error when rendering to .pdf

### ISSUE THREAD

**Issue by mikeroswell** [yihui/knitr#2234]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

--

Error knitting to .pdf from .rmd seems to occur with `warnings` generated by **dplyr**, suggesting a problem with a unicode escape. 

I was able to reproduce with this

````markdown
---
title: "special_i"
author: "Michael Roswell"
date: "2023-02-24"
output: 
  pdf_document: 
    latex_engine: pdflatex
---
seems like the dplyr warning message creates problems with 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```
```{r create a warning}
mtcars[1,"carb"] <- NA
mtcars %>% summarize_all(sqrt)
```
````

```
> xfun::session_info('knitr')
R version 4.2.2 (2022-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1, RStudio 2022.12.0.353

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  evaluate_0.20   graphics_4.2.2  grDevices_4.2.2 highr_0.10      knitr_1.42     
  methods_4.2.2   stats_4.2.2     tools_4.2.2     utils_4.2.2     xfun_0.37      
  yaml_2.3.7     
```

https://stackoverflow.com/q/75504968/8400969

**Comment by mikeroswell** [comment]
c.f.  #2231

**Comment by cderv** [comment]
For more context, this is the emitted warning that shows in knitted output with dplyr 
![image](https://user-images.githubusercontent.com/6791940/221622727-9795d676-c6d4-4be7-8d99-65664cb779a7.png)

It does not seems like the output link is correct for support with **knitr**. I think this is an issue with **dplyr** or maybe **cli** which should be what is used there. 

Usually the ANSI code formatting for **cli** use to get nice output in console should be deactivating when knitting. 

See also with `html_document()`

![image](https://user-images.githubusercontent.com/6791940/221623414-e81de888-23ff-4361-a6c5-8948fe76c0fa.png)


BTW regarding #2231, this is a matter of latex_engine, and **xelatex** should be used when unicode 
https://bookdown.org/yihui/rmarkdown-cookbook/latex-unicode.html

It does not solve issue here, because I think there is something that shouldn't be printed anyway.

**Comment by mikeroswell** [comment]
Looks like it's on their radar: https://github.com/r-lib/cli/issues/581#issue-1576635242

**Comment by cderv** [comment]
yes thanks, I was writing a message there. Didn't know you where also digging into that.

**Comment by mikeroswell** [comment]
Thanks, your message was more helpful! Since I had complained in the first place, I figured it might be my job to close the loop.

**Comment by gaborcsardi** [comment]
This should be fixed in dev cli: https://github.com/r-lib/cli/issues/581
Can you please confirm?

**Comment by cderv** [comment]
It works for me now with your example @mikeroswell and dev **cli**
