### ISSUE TITLE
Building quarto book shows non-interactive progress bar

### ISSUE THREAD

**Issue by hadley** [yihui/knitr#2271]
i.e.

```
processing file: names.Rmd
1/31                   
2/31 [unnamed-chunk-1] 
3/31                   
4/31 [unnamed-chunk-2] 
5/31                   
6/31 [unnamed-chunk-3] 
7/31                   
8/31 [unnamed-chunk-4] 
9/31                   
```

Previously it was (correctly) using the dynamic progress bar. I'm using knitr 1.43.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('knitr')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('yihui/knitr')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by hadley** [comment]
Same problem when knitting a single quarto doc when the output appears in the background jobs tab, rather than the build pane.

**Comment by cderv** [comment]
> Previously it was (correctly) using the dynamic progress bar.

The new behavior cames from discussion in https://github.com/yihui/knitr/issues/2221 and commit https://github.com/yihui/knitr/commit/47bce017a506ee43e4b325547804ee7438910a59

It was introduced in [1.43](https://github.com/yihui/knitr/blob/master/NEWS.md#changes-in-knitr-version-143)

Current detection for simple mode is 
https://github.com/yihui/knitr/blob/ec4c9b632e1b35994340848884a31da2ca24640a/R/utils.R#L1136-L1149

When quarto is running R it will do it executing R in background session started with Deno as `Rscript <file>`. None of the specific checks return FALSE to no activate simple mode , and **knitr** will then detect that it is not running in RStudio IDE so activate the `simple` version  (`is.null(tryCatch(rstudioapi::versionInfo(), error = function(e) NULL))` returns TRUE

So probably the current detection does not work for the case of **knitr** run within Quarto. We need to find what works for this case....

**Comment by yihui** [comment]
> We need to find what works for this case....

I'm using an env var to detect the background jobs pane. This should work now.

**Comment by cderv** [comment]
> This should work now.

This is now working in Background Job pane inside RStudio. 

> rather than the build pane.

@hadley I understand there could be a scenario where the Build pane is used ? 

Also, I don't know if you were referring only to RStudio IDE panes, but just for referement, in terminal, it will still use the non-interactive progress bar. In same terminal session, we'll have

* `Rscript -e 'rmarkdown::render("index.qmd")` showing us the full progress bar 
  * This means the **knitr** detection sees that non-simple progress bar can be used 
* `quarto render index.qmd` showing us the simple progress bar
  * This means the **knitr** detection decide that simple progress bar should be used. Probably because background R process as I mentioned previously. 

Just mentioning this for reference. The simple progress bar seems ok to have in Terminal for Quarto.

**Comment by hadley** [comment]
Yeah, I see it quarto book usually in the build pane.

**Comment by cderv** [comment]
Thanks I tried Quarto Website and the Build Pane button triggers a render in the Job Pane. 

So it seems only the Build button for a Quarto Book triggers rendering in the Build pane directly.

**Comment by cderv** [comment]
It should be ok in build pane now too. thanks

**Comment by hadley** [comment]
Thanks @cderv!
