### ISSUE TITLE
[spin] Better support for `#|` to split cell in .qmd

### ISSUE THREAD

**Issue by cderv** [yihui/knitr#2314]
``` r
knitr::spin(text = c('#| echo: false','1+1', '#| label: test','1+1'), format = 'qmd', knit = F) |> xfun::raw_string()
#> 
#> ```{r}
#> #| echo: false
#> 1+1
#> #| eval: false
#> 1+1
#> ```
```

This is producing wrong syntax in .qmd really correct or ideal, considering `#+` does correcty split

``` r
knitr::spin(text = c('#+ echo = FALSE','1+1', '#+ eval=FALSE','1+1'), format = 'qmd', knit = F) |> xfun::raw_string()
#> 
#> ```{r echo = FALSE}
#> 1+1
#> ```
#> ```{r eval=FALSE}
#> 1+1
#> ```
```

**Comment by kylebutts** [comment]
@cderv I'm confused by this. What is the intended output of the first example? 

From my understanding of the internals of `knitr::spin`, `#|` are ignored, so they work sort of by accident. Is your expectation that a lone `#|` would produce a code chunk? 

In the second example, `#+` marks code cells, so they're demarkating code chunks.

**Comment by kylebutts** [comment]
Is the goal this? 

#> ```{r}
#> #| echo: false
#> 1+1
#> #| eval: false
#> 1+1
#> ```

`````

**Comment by kylebutts** [comment]
Ahh, yes! I agree. That `#|` works is just because it is left alone by `knitr::spin()`. 

Just to be clear, you think the result of your first code block should be:

````` r
```{r}
#| echo: false
1+1
```
```{r}
#| eval: false
1+1
```
`````

I can submit a PR for this.  I think there's two modifications that should occur:
1. `#|` should be treated as a code chunk marker
2. Any `#|` that are immediately following *any* code marker should be left as is. 

Does that seem right to you? And would this would only be with `format = 'qmd'`? 

BTW, this change would also touch the R VSCode extension, https://github.com/REditorSupport/vscode-R/pull/1455, so I'll have to add a PR there too

**Comment by kylebutts** [comment]
@cderv Fixed in my fork: https://github.com/kylebutts/knitr/commit/b8e17d736ee557acc5f5714c5a4289ef20416857. What do you think about the approach? It basically inserts a `# %%` whenever a code chunk starts with `#|` and then runs spin as normal. 

I was thinking of refactoring that part of spin to loop through the lines and mark `chunk_start` and `chunk_end`. This might make the code more readable / simple, but is more of an invasive/bug-prone change.

**Comment by cderv** [comment]
Thanks for giving it a try ! Can you open a PR even as draft ? This makes it more easy to compare and review. @yihui will also be able to jump in and give its thoughts. 

Thanks!

**Comment by yihui** [comment]
I forgot to close this issue when merging https://github.com/yihui/knitr/pull/2320.
