### ISSUE TITLE
LaTeX figure rotation

### ISSUE THREAD

**Issue by knokknok** [yihui/knitr#301]
Do you think you could add a fig.angle chunk option?

Thanks!

**Comment by SFrav** [comment]
Are there any plans to have similar features for R markdown knitr output to Word? Rotate and page break.

**Comment by langtonhugh** [comment]
Using out.extra='angle=90' works beautifully, but the caption does not rotate with it. Is there a way to include the caption in the rotate?

**Comment by alqadker** [comment]
@langtonhugh  @yihui 
Hi There!
I am experiencing the same problem as @langtonhugh did you did back in 2019.
Did anybody manage to rotate the caption with the figure too? If so, it would be very much appriciated.

Thanks

**Comment by langtonhugh** [comment]
For figures and tables, I have been using \begin{landscape} and \end{landscape} either side of the code chunk outputting the figure or table. Looking at some old files, I can see that I sometimes **also** use out.extra='angle=90' for tables. I am not sure whether this makes a difference, but it does work.

**Comment by alqadker** [comment]
@langtonhugh 
Thanky you so much for replying so fast! It worked.

I will leave this here for anybody else encountering the same problem.

If you want to rotate the caption with the figure you do this: 

\begin{landscape}
```{r image, echo = FALSE, fig.scap="This is the caption List of figures", fig.cap = "This is the caption underneath the figure.", fig.align= "center", results = "asis", fig.show='hold', out.width = "100%", fig.pos = "H"}
\end{landscape}


You simply want to rotate the figure in cases where no caption is included/needed:

```{r image, echo = FALSE, fig.scap="This is the caption List of figures", fig.cap = "This is the caption underneath the figure.", fig.align= "center", results = "asis", fig.show='hold', out.width = "100%", fig.pos = "H", out.extra='angle=90'}

keep in mind that  adding fig.pos = "H" may be necessary if a caption is included because you could encounter the problem of  figure desplacement when knitting to pdf with tex.

Thank you
