### ISSUE TITLE
adding plots and markdown from a for loop

### ISSUE THREAD

**Issue by nesono** [yihui/knitr#408]
Hi, I hope this is neither a bug and nor has been reported already ;)
I have a problem with plotting and pasting markdown from within a for loop.

The problem can be reproduced using the following listing:

``` r fig.width=7, fig.height=6, fig.show='asis', fig.keep='all', results='asis'
for( idx in seq(4) ) {
  cat( paste('## title no.', idx, '\n' ) ) 
  plot(cars)
  cat('\n\n')
  }
```

I always get the following

``` markdown
## title no. 1

## title no. 2

[figure]

## title no. 3

[figure]

## title no. 4
```

Do I miss something or is there a bug in plotting from within a for loop.
Or do I misuse?

Best,

jochen

**Comment by happyshows** [comment]
---
title: "`readthedown` template example"
date: "`r Sys.Date()`"
author: 
output: html_document
---


# Code and tables


```{r fig.cap="This is a caption"}
for( idx in seq(4) ) {
  cat( paste('## title no.', idx, '\n' ) ) 
  plot(cars)
  cat('\n\n')
  }
```

I just ran this and this issue seems to come back again

**Comment by yihui** [comment]
@happyshows That is mainly because you were drawing exactly the same plot over and over again in the loop. knitr does not preserve identical consecutive plots. If the plot is different in each step of the loop, you will see them, e.g.

    ---
    title: "`readthedown` template example"
    date: "`r Sys.Date()`"
    author: 
    output: html_document
    ---
    
    
    # Code and tables
    
    ```{r fig.cap="This is a caption"}
    for( idx in seq(4) ) {
      cat( paste('## title no.', idx, '\n' ) ) 
      plot(rnorm(100))
      cat('\n\n')
      }
    ```

**Comment by happyshows** [comment]
@yihui    [Please let me know if I need to start a new issue to discuss this]
Could you also take a look at my SO question? [linky](http://stackoverflow.com/questions/39421343/loop-to-generate-plotly-charts-with-comments-in-rmd)

I was trying to generate a list of headers + plotly objects.  I tried the child.Rmd approach, it didn't seem to render the plotly object properly.

What function will facilitate to generate .Rmd on the fly and convert that into HTML? I want to generate something like via loop:
#header 1
plotly(1)

#header 2
plotly(2)

etc.

So that I can take advantage of  rmdformats::readthedown theme which makes a long report look nicer.

My current code looks like below: referencing an approach suggested by @timelyportfolio . However, I do not necessarily want to collate all header+objects into tabset.
```
```{r include=FALSE, results='asis'}
library(plotly)
library(htmltools)
library(magrittr)
library(archivist)

setLocalRepo(params$repo)
plots <- lapply(params$ls_md5,function(md5){
  aread(md5)
})
names(plots) <- names(params$ls_md5)

tab_bodies <- lapply(names(plots),function(p){
  tags$div(
    cat(plots[[p]]$comment),
    plots[[p]]$viz,
    hr()
  )
})

txt <- tags$div(tab_bodies) %>%
  attachDependencies(
    list(
      rmarkdown::html_dependency_jquery(),
      shiny::bootstrapLib()
    )
  )
```
```

**Comment by happyshows** [comment]
a follow up complement:
how do I plug in an unevaluated paste0("# header",plots[[p]]$comment) into the loop so that the # header will be picked up by readthedown theme?
