### ISSUE TITLE
figure.env \label placement

### ISSUE THREAD

**Issue by dr-moebius** [yihui/knitr#746]
using fig.env puts \label{...} inside \caption{...} like this:
```latex
\caption{this is a caption\label{label}}
```
this is not recommended, \label{} should be after \caption{} like this:

```latex
\caption{this is a caption}\label{label}
```
the label can get lost using the latex package ```caption``` and calling ```\captionsetup{}```.

**Comment by ltorgo** [comment]
I would like to ask to re-open this issue because it is affecting me considerably and I do think the problem extends beyond the latex package caption. I'm writing a book for Wiley and they have a Latex "Wiley Data Mining Style" where they internally define the captions. Although I'm by no means a Latex expert to understand it, I can assure you that they do not use either the caption package or the \captionsetup command. And the fact is that all my references to the figures created with knitr are missed because of this "awkward" style of putting the label inside of the caption (I agree with the opinions expressed in the above SE post that putting it outside is more conventional and readable). 

So this "problem" has impact beyond the caption latex package and thus I would like to ask Yihui if he could think twice on changing this... I can of course try to overcome this by some kind of more or less complex post-processing of the knitr output but I would prefer a "cleaner" solution...

Thank you for any help on this and also for the excellent knitr tool ;-)

**Comment by ltorgo** [comment]
To put the \label outside of \caption wouldn't it be enough to change line 124 of file hooks-latex.R from:
    fig2 = sprintf('\\caption%s{%s\\label{%s}}\n\\end{%s}\n', scap, cap,
to:
    fig2 = sprintf('\\caption%s{%s}\\label{%s}\n\\end{%s}\n', scap, cap,
?

**Comment by yihui** [comment]
@ltorgo Yes, it probably takes 10 seconds for me to make that change. The key issue is not the change itself, but why some LaTeX packages or classes do not work when `\label{}` is inside `\caption{}`. Personally I'm more comfortable with the label inside caption. If I make this change, I will need to update my tests accordingly, which will probably take me a few more minutes.

Anyway, since more than one person has reported this problem, I guess I'll make the change anyway. Let me see if I can do it today. Thanks!

**Comment by yihui** [comment]
I have made the change.

**Comment by ltorgo** [comment]
Thank you! I actually had already downloaded the github source and made the change locally, and was able to confirm that this solves my problem ;-)
