### ISSUE TITLE
Include \Sexpr in purl output

### ISSUE THREAD

**Issue by kendonB** [yihui/knitr#948]
I'm having trouble debugging a large .Rnw file. Is there a way to get the \Sexpr{} expressions into
a purl output?

Alternatively, do you have a nice way to debug large .Rnw files? i.e. using RStudio debug tools on an .Rnw?

Thanks so much,
Kenny

**Comment by yihui** [comment]
No, most of the time I just use the old-fashioned `print()` :)

Personally I'm not very interested in `purl()`, and I do not recommend you to put too complicated R expressions in `\Sexpr{}`. I guess I'm unlikely to spend more time on it.

If you have R functions in the code chunks and want to debug them, I think you can use the normal debugging techniques like `debug()` or `browser()`, and just call `knit()` in the R console instead of clicking the button. I'd recommend you to put functions in R packages, though, if there are many of them in the Rnw document.

**Comment by kendonB** [comment]
Hi,

I personally only use Sexpr for getting values of variables, usually wrapped in prettyNum. I made a mistake in one of my many prettyNums which produced the error. When I have many of these calls between compiles, I can make mistakes. 

Anyway, I ended up using Ctrl+F and visually looking through the Sexprs and that worked fine.

On Thursday Jan 29, 2015 at 12:26 AM, Yihui Xie <notifications@github.com>, wrote:

No, most of the time I just use the old-fashioned `print()` :)

Personally I'm not very interested in `purl()`, and I do not recommend you to put too complicated R expressions in `\Sexpr{}`. I guess I'm unlikely to spend more time on it.

If you have R functions in the code chunks and want to debug them, I think you can use the normal debugging techniques like `debug()` or `browser()`, and just call `knit()` in the R console instead of clicking the button. I'd recommend you to put functions in R packages, though, if there are many of them in the Rnw document.

---
